/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../angularApp/app/login/components/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../angularApp/app/app.constants';
import * as import9 from '../../../../../angularApp/app/core/services/account.service';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/core/src/security';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import18 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import19 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import23 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import24 from '../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import25 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import26 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import27 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import28 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import29 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import30 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import31 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import32 from '@angular/router/src/router_state';
import * as import33 from '@angular/common/src/directives/ng_for';
import * as import34 from '@angular/common/src/directives/ng_class';
import * as import35 from '@angular/forms/src/directives/validators';
import * as import36 from '@angular/forms/src/validators';
import * as import37 from '@angular/forms/src/directives/control_value_accessor';
import * as import38 from '@angular/forms/src/directives/ng_model';
import * as import39 from '@angular/forms/src/directives/ng_control';
import * as import40 from '@angular/forms/src/directives/ng_control_status';
import * as import41 from '@angular/forms/src/directives/default_value_accessor';
import * as import42 from '@angular/router/src/directives/router_link';
import * as import43 from '@angular/forms/src/directives/ng_form';
import * as import44 from '@angular/forms/src/directives/control_container';
export class Wrapper_LoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.LoginComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginComponent>;
  _LoginComponent_0_3:Wrapper_LoginComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent_Host0,renderType_LoginComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'login-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LoginComponent0(this.viewUtils,this,0,this._el_0);
    this._LoginComponent_0_3 = new Wrapper_LoginComponent(this.injectorGet(import8.Configuration,this.parentIndex),this.injectorGet(import9.AccountService,this.parentIndex),this.injectorGet(import10.Router,this.parentIndex));
    this.compView_0.create(this._LoginComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LoginComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginComponentNgFactory:import7.ComponentFactory<import0.LoginComponent> = new import7.ComponentFactory<import0.LoginComponent>('login-component',View_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = ([] as any[]);
class View_LoginComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent1,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.context.message;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent2 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import14.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import15.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent2,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import14.Wrapper_NgSelectOption(new import16.ElementRef(this._el_0),this.renderer,(<View_LoginComponent0>this.parentView)._SelectControlValueAccessor_32_4.context);
    this._NgSelectMultipleOption_0_4 = new import15.Wrapper_NgSelectMultipleOption(new import16.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import18.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit.code;
    this._NgSelectOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit.code;
    this._NgSelectMultipleOption_0_4.check_value(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent4,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            El tipo de documento es requerido.\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent3,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (<View_LoginComponent0>this.parentView)._NgModel_32_8.context.hasError('required');
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_LoginComponent4(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_LoginComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent6,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            El documento es requerido.\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent5,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (<View_LoginComponent0>this.parentView)._NgModel_42_8.context.hasError('required');
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_LoginComponent6(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_LoginComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent8,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            La contraseña es requerida.\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent7,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (<View_LoginComponent0>this.parentView)._NgModel_49_8.context.hasError('required');
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_LoginComponent8(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_LoginComponent9 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import14.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import15.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent9,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import14.Wrapper_NgSelectOption(new import16.ElementRef(this._el_0),this.renderer,(<View_LoginComponent0>this.parentView)._SelectControlValueAccessor_56_4.context);
    this._NgSelectMultipleOption_0_4 = new import15.Wrapper_NgSelectMultipleOption(new import16.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import18.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit.code;
    this._NgSelectOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit.code;
    this._NgSelectMultipleOption_0_4.check_value(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent11 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent11,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            El tipo de usuario es requerido.\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent10 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent10,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (<View_LoginComponent0>this.parentView)._NgModel_56_8.context.hasError('required');
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_LoginComponent11(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_LoginComponent12 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_LoginComponent12,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'height','24','src','/assets/spin.svg','width','24'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_LoginComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_LoginComponent,{});
export class View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import11.ViewContainer;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import19.Wrapper_NgIf;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _NgForm_26_3:import22.Wrapper_NgForm;
  _ControlContainer_26_4:any;
  _NgControlStatusGroup_26_5:import23.Wrapper_NgControlStatusGroup;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _NgClass_32_3:import24.Wrapper_NgClass;
  _SelectControlValueAccessor_32_4:import14.Wrapper_SelectControlValueAccessor;
  _RequiredValidator_32_5:import25.Wrapper_RequiredValidator;
  _NG_VALIDATORS_32_6:any[];
  _NG_VALUE_ACCESSOR_32_7:any[];
  _NgModel_32_8:import26.Wrapper_NgModel;
  _NgControl_32_9:any;
  _NgControlStatus_32_10:import23.Wrapper_NgControlStatus;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _vc_34:import11.ViewContainer;
  _TemplateRef_34_5:any;
  _NgFor_34_6:import27.Wrapper_NgFor;
  _text_35:any;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _vc_37:import11.ViewContainer;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import19.Wrapper_NgIf;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _NgClass_42_3:import24.Wrapper_NgClass;
  _DefaultValueAccessor_42_4:import28.Wrapper_DefaultValueAccessor;
  _RequiredValidator_42_5:import25.Wrapper_RequiredValidator;
  _NG_VALIDATORS_42_6:any[];
  _NG_VALUE_ACCESSOR_42_7:any[];
  _NgModel_42_8:import26.Wrapper_NgModel;
  _NgControl_42_9:any;
  _NgControlStatus_42_10:import23.Wrapper_NgControlStatus;
  _text_43:any;
  _anchor_44:any;
  /*private*/ _vc_44:import11.ViewContainer;
  _TemplateRef_44_5:any;
  _NgIf_44_6:import19.Wrapper_NgIf;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _NgClass_49_3:import24.Wrapper_NgClass;
  _DefaultValueAccessor_49_4:import28.Wrapper_DefaultValueAccessor;
  _RequiredValidator_49_5:import25.Wrapper_RequiredValidator;
  _NG_VALIDATORS_49_6:any[];
  _NG_VALUE_ACCESSOR_49_7:any[];
  _NgModel_49_8:import26.Wrapper_NgModel;
  _NgControl_49_9:any;
  _NgControlStatus_49_10:import23.Wrapper_NgControlStatus;
  _text_50:any;
  _anchor_51:any;
  /*private*/ _vc_51:import11.ViewContainer;
  _TemplateRef_51_5:any;
  _NgIf_51_6:import19.Wrapper_NgIf;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _NgClass_56_3:import24.Wrapper_NgClass;
  _SelectControlValueAccessor_56_4:import14.Wrapper_SelectControlValueAccessor;
  _RequiredValidator_56_5:import25.Wrapper_RequiredValidator;
  _NG_VALIDATORS_56_6:any[];
  _NG_VALUE_ACCESSOR_56_7:any[];
  _NgModel_56_8:import26.Wrapper_NgModel;
  _NgControl_56_9:any;
  _NgControlStatus_56_10:import23.Wrapper_NgControlStatus;
  _text_57:any;
  _anchor_58:any;
  /*private*/ _vc_58:import11.ViewContainer;
  _TemplateRef_58_5:any;
  _NgFor_58_6:import27.Wrapper_NgFor;
  _text_59:any;
  _text_60:any;
  _anchor_61:any;
  /*private*/ _vc_61:import11.ViewContainer;
  _TemplateRef_61_5:any;
  _NgIf_61_6:import19.Wrapper_NgIf;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _RouterLink_71_3:import29.Wrapper_RouterLink;
  _text_72:any;
  _text_73:any;
  _anchor_74:any;
  /*private*/ _vc_74:import11.ViewContainer;
  _TemplateRef_74_5:any;
  _NgIf_74_6:import19.Wrapper_NgIf;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _map_156:any;
  _map_157:any;
  _map_158:any;
  _map_159:any;
  /*private*/ _expr_160:any;
  _arr_161:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent0,renderType_LoginComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_156 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {InputError: p0};
    });
    this._map_157 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {InputError: p0};
    });
    this._map_158 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {InputError: p0};
    });
    this._map_159 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {InputError: p0};
    });
    this._expr_160 = import12.UNINITIALIZED;
    this._arr_161 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','bgLogin'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row vertical-offset-100'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-4 col-md-offset-4'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'p',new import3.InlineArray2(2,'class','headerForm'),(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_12 = new import11.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import20.TemplateRef_(this,12,this._anchor_12);
    this._NgIf_12_6 = new import19.Wrapper_NgIf(this._vc_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'h3',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_19,'span',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Resultados en línea',(null as any));
    this._text_22 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'form',new import3.InlineArray4(4,'novalidate','','role','form'),(null as any));
    this._NgForm_26_3 = new import22.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_26_4 = this._NgForm_26_3.context;
    this._NgControlStatusGroup_26_5 = new import23.Wrapper_NgControlStatusGroup(this._ControlContainer_26_4);
    this._text_27 = this.renderer.createText(this._el_26,'\n                            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'fieldset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                                ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                                    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'select',new import3.InlineArray8(8,'class','form-control','id','docType','name','docType','required',''),(null as any));
    this._NgClass_32_3 = new import24.Wrapper_NgClass(this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import31.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_32),this.renderer);
    this._SelectControlValueAccessor_32_4 = new import14.Wrapper_SelectControlValueAccessor(this.renderer,new import16.ElementRef(this._el_32));
    this._RequiredValidator_32_5 = new import25.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_32_6 = [this._RequiredValidator_32_5.context];
    this._NG_VALUE_ACCESSOR_32_7 = [this._SelectControlValueAccessor_32_4.context];
    this._NgModel_32_8 = new import26.Wrapper_NgModel(this._ControlContainer_26_4,this._NG_VALIDATORS_32_6,(null as any),this._NG_VALUE_ACCESSOR_32_7);
    this._NgControl_32_9 = this._NgModel_32_8.context;
    this._NgControlStatus_32_10 = new import23.Wrapper_NgControlStatus(this._NgControl_32_9);
    this._text_33 = this.renderer.createText(this._el_32,'\n                                        ',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_32,(null as any));
    this._vc_34 = new import11.ViewContainer(34,32,this,this._anchor_34);
    this._TemplateRef_34_5 = new import20.TemplateRef_(this,34,this._anchor_34);
    this._NgFor_34_6 = new import27.Wrapper_NgFor(this._vc_34.vcRef,this._TemplateRef_34_5,this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.ref);
    this._text_35 = this.renderer.createText(this._el_32,'\n                                    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_30,'\n                                    ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_30,(null as any));
    this._vc_37 = new import11.ViewContainer(37,30,this,this._anchor_37);
    this._TemplateRef_37_5 = new import20.TemplateRef_(this,37,this._anchor_37);
    this._NgIf_37_6 = new import19.Wrapper_NgIf(this._vc_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_30,'\n                                ',(null as any));
    this._text_39 = this.renderer.createText(this._el_28,'\n                                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                                    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'input',new import3.InlineArray16(16,'autocomplete','off','autofocus','','class','form-control','id','docId','name','docId','placeholder','Número de documento','required','','type','text'),(null as any));
    this._NgClass_42_3 = new import24.Wrapper_NgClass(this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import31.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_42),this.renderer);
    this._DefaultValueAccessor_42_4 = new import28.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_42));
    this._RequiredValidator_42_5 = new import25.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_42_6 = [this._RequiredValidator_42_5.context];
    this._NG_VALUE_ACCESSOR_42_7 = [this._DefaultValueAccessor_42_4.context];
    this._NgModel_42_8 = new import26.Wrapper_NgModel(this._ControlContainer_26_4,this._NG_VALIDATORS_42_6,(null as any),this._NG_VALUE_ACCESSOR_42_7);
    this._NgControl_42_9 = this._NgModel_42_8.context;
    this._NgControlStatus_42_10 = new import23.Wrapper_NgControlStatus(this._NgControl_42_9);
    this._text_43 = this.renderer.createText(this._el_40,'\n                                    ',(null as any));
    this._anchor_44 = this.renderer.createTemplateAnchor(this._el_40,(null as any));
    this._vc_44 = new import11.ViewContainer(44,40,this,this._anchor_44);
    this._TemplateRef_44_5 = new import20.TemplateRef_(this,44,this._anchor_44);
    this._NgIf_44_6 = new import19.Wrapper_NgIf(this._vc_44.vcRef,this._TemplateRef_44_5);
    this._text_45 = this.renderer.createText(this._el_40,'\n                                ',(null as any));
    this._text_46 = this.renderer.createText(this._el_28,'\n                                ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                                    ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'input',new import3.InlineArray16(16,'autocomplete','off','class','form-control','id','pwd','name','pwd','placeholder','Contraseña','required','','type','password','value',''),(null as any));
    this._NgClass_49_3 = new import24.Wrapper_NgClass(this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import31.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_49),this.renderer);
    this._DefaultValueAccessor_49_4 = new import28.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_49));
    this._RequiredValidator_49_5 = new import25.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_49_6 = [this._RequiredValidator_49_5.context];
    this._NG_VALUE_ACCESSOR_49_7 = [this._DefaultValueAccessor_49_4.context];
    this._NgModel_49_8 = new import26.Wrapper_NgModel(this._ControlContainer_26_4,this._NG_VALIDATORS_49_6,(null as any),this._NG_VALUE_ACCESSOR_49_7);
    this._NgControl_49_9 = this._NgModel_49_8.context;
    this._NgControlStatus_49_10 = new import23.Wrapper_NgControlStatus(this._NgControl_49_9);
    this._text_50 = this.renderer.createText(this._el_47,'\n                                    ',(null as any));
    this._anchor_51 = this.renderer.createTemplateAnchor(this._el_47,(null as any));
    this._vc_51 = new import11.ViewContainer(51,47,this,this._anchor_51);
    this._TemplateRef_51_5 = new import20.TemplateRef_(this,51,this._anchor_51);
    this._NgIf_51_6 = new import19.Wrapper_NgIf(this._vc_51.vcRef,this._TemplateRef_51_5);
    this._text_52 = this.renderer.createText(this._el_47,'\n                                ',(null as any));
    this._text_53 = this.renderer.createText(this._el_28,'\n                                ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                                    ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'select',new import3.InlineArray8(8,'class','form-control','id','userType','name','userType','required',''),(null as any));
    this._NgClass_56_3 = new import24.Wrapper_NgClass(this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import31.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_56),this.renderer);
    this._SelectControlValueAccessor_56_4 = new import14.Wrapper_SelectControlValueAccessor(this.renderer,new import16.ElementRef(this._el_56));
    this._RequiredValidator_56_5 = new import25.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_56_6 = [this._RequiredValidator_56_5.context];
    this._NG_VALUE_ACCESSOR_56_7 = [this._SelectControlValueAccessor_56_4.context];
    this._NgModel_56_8 = new import26.Wrapper_NgModel(this._ControlContainer_26_4,this._NG_VALIDATORS_56_6,(null as any),this._NG_VALUE_ACCESSOR_56_7);
    this._NgControl_56_9 = this._NgModel_56_8.context;
    this._NgControlStatus_56_10 = new import23.Wrapper_NgControlStatus(this._NgControl_56_9);
    this._text_57 = this.renderer.createText(this._el_56,'\n                                        ',(null as any));
    this._anchor_58 = this.renderer.createTemplateAnchor(this._el_56,(null as any));
    this._vc_58 = new import11.ViewContainer(58,56,this,this._anchor_58);
    this._TemplateRef_58_5 = new import20.TemplateRef_(this,58,this._anchor_58);
    this._NgFor_58_6 = new import27.Wrapper_NgFor(this._vc_58.vcRef,this._TemplateRef_58_5,this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.ref);
    this._text_59 = this.renderer.createText(this._el_56,'\n                                    ',(null as any));
    this._text_60 = this.renderer.createText(this._el_54,'\n                                    ',(null as any));
    this._anchor_61 = this.renderer.createTemplateAnchor(this._el_54,(null as any));
    this._vc_61 = new import11.ViewContainer(61,54,this,this._anchor_61);
    this._TemplateRef_61_5 = new import20.TemplateRef_(this,61,this._anchor_61);
    this._NgIf_61_6 = new import19.Wrapper_NgIf(this._vc_61.vcRef,this._TemplateRef_61_5);
    this._text_62 = this.renderer.createText(this._el_54,'\n                                ',(null as any));
    this._text_63 = this.renderer.createText(this._el_28,'\n                                ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_28,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'\n                                    ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_64,'div',new import3.InlineArray2(2,'class','col-6'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n                                        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'button',new import3.InlineArray4(4,'class','btn btn-warning px-2','type','submit'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Acceder',(null as any));
    this._text_70 = this.renderer.createText(this._el_66,'\n                                        ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_66,'button',new import3.InlineArray4(4,'class','btn btn-link px-0 text-right','type','button'),(null as any));
    this._RouterLink_71_3 = new import29.Wrapper_RouterLink(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import32.ActivatedRoute,this.parentIndex));
    this._text_72 = this.renderer.createText(this._el_71,'¿Olvidó contraseña?',(null as any));
    this._text_73 = this.renderer.createText(this._el_66,'\n                                        ',(null as any));
    this._anchor_74 = this.renderer.createTemplateAnchor(this._el_66,(null as any));
    this._vc_74 = new import11.ViewContainer(74,66,this,this._anchor_74);
    this._TemplateRef_74_5 = new import20.TemplateRef_(this,74,this._anchor_74);
    this._NgIf_74_6 = new import19.Wrapper_NgIf(this._vc_74.vcRef,this._TemplateRef_74_5);
    this._text_75 = this.renderer.createText(this._el_66,'\n                                    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_64,'\n                                ',(null as any));
    this._text_77 = this.renderer.createText(this._el_28,'\n                            ',(null as any));
    this._text_78 = this.renderer.createText(this._el_26,'\n                        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._text_80 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._text_81 = this.renderer.createText(this._el_6,'\n\n                ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'\n                    ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_82,'div',new import3.InlineArray2(2,'style','color: #00748A; background-color: #eee; text-align: center; width:auto;'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n                        ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_84,'div',new import3.InlineArray2(2,'style','padding-left: 10px; padding-right: 10px; margin-left: 10px; margin-right: 10px;'),(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'\n                            Cualquier inquietud  por favor comunicarse al 4440019 extensión 125.\n                            ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_86,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_89 = this.renderer.createText(this._el_86,'\n                            Le recomendamos usar los navegadores Web Chrome 43 o superior, Firefox 38 o superior, Safari 8 o superior, Internet Explorer 10, 11.\n                        ',(null as any));
    this._text_90 = this.renderer.createText(this._el_84,'\n                    ',(null as any));
    this._text_91 = this.renderer.createText(this._el_82,'\n                ',(null as any));
    this._text_92 = this.renderer.createText(this._el_6,'\n\n            ',(null as any));
    this._text_93 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_94 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_95 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_26));
    this._NgForm_26_3.subscribe(this,this.eventHandler(this.handleEvent_26),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_32,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_32));
    this._NgModel_32_8.subscribe(this,this.eventHandler(this.handleEvent_32),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_42));
    this._NgModel_42_8.subscribe(this,this.eventHandler(this.handleEvent_42),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_49,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_49));
    this._NgModel_49_8.subscribe(this,this.eventHandler(this.handleEvent_49),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_56,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_56));
    this._NgModel_56_8.subscribe(this,this.eventHandler(this.handleEvent_56),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_71,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_71));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._anchor_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._anchor_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._anchor_58,
      this._text_59,
      this._text_60,
      this._anchor_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._anchor_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._text_95
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import21.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    if (((token === import20.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import33.NgFor) && (34 === requestNodeIndex))) { return this._NgFor_34_6.context; }
    if (((token === import34.NgClass) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgClass_32_3.context; }
    if (((token === import17.SelectControlValueAccessor) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._SelectControlValueAccessor_32_4.context; }
    if (((token === import35.RequiredValidator) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._RequiredValidator_32_5.context; }
    if (((token === import36.NG_VALIDATORS) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NG_VALIDATORS_32_6; }
    if (((token === import37.NG_VALUE_ACCESSOR) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NG_VALUE_ACCESSOR_32_7; }
    if (((token === import38.NgModel) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgModel_32_8.context; }
    if (((token === import39.NgControl) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControl_32_9; }
    if (((token === import40.NgControlStatus) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControlStatus_32_10.context; }
    if (((token === import20.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import21.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6.context; }
    if (((token === import34.NgClass) && (42 === requestNodeIndex))) { return this._NgClass_42_3.context; }
    if (((token === import41.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_4.context; }
    if (((token === import35.RequiredValidator) && (42 === requestNodeIndex))) { return this._RequiredValidator_42_5.context; }
    if (((token === import36.NG_VALIDATORS) && (42 === requestNodeIndex))) { return this._NG_VALIDATORS_42_6; }
    if (((token === import37.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_7; }
    if (((token === import38.NgModel) && (42 === requestNodeIndex))) { return this._NgModel_42_8.context; }
    if (((token === import39.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_9; }
    if (((token === import40.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_10.context; }
    if (((token === import20.TemplateRef) && (44 === requestNodeIndex))) { return this._TemplateRef_44_5; }
    if (((token === import21.NgIf) && (44 === requestNodeIndex))) { return this._NgIf_44_6.context; }
    if (((token === import34.NgClass) && (49 === requestNodeIndex))) { return this._NgClass_49_3.context; }
    if (((token === import41.DefaultValueAccessor) && (49 === requestNodeIndex))) { return this._DefaultValueAccessor_49_4.context; }
    if (((token === import35.RequiredValidator) && (49 === requestNodeIndex))) { return this._RequiredValidator_49_5.context; }
    if (((token === import36.NG_VALIDATORS) && (49 === requestNodeIndex))) { return this._NG_VALIDATORS_49_6; }
    if (((token === import37.NG_VALUE_ACCESSOR) && (49 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_49_7; }
    if (((token === import38.NgModel) && (49 === requestNodeIndex))) { return this._NgModel_49_8.context; }
    if (((token === import39.NgControl) && (49 === requestNodeIndex))) { return this._NgControl_49_9; }
    if (((token === import40.NgControlStatus) && (49 === requestNodeIndex))) { return this._NgControlStatus_49_10.context; }
    if (((token === import20.TemplateRef) && (51 === requestNodeIndex))) { return this._TemplateRef_51_5; }
    if (((token === import21.NgIf) && (51 === requestNodeIndex))) { return this._NgIf_51_6.context; }
    if (((token === import20.TemplateRef) && (58 === requestNodeIndex))) { return this._TemplateRef_58_5; }
    if (((token === import33.NgFor) && (58 === requestNodeIndex))) { return this._NgFor_58_6.context; }
    if (((token === import34.NgClass) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgClass_56_3.context; }
    if (((token === import17.SelectControlValueAccessor) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._SelectControlValueAccessor_56_4.context; }
    if (((token === import35.RequiredValidator) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._RequiredValidator_56_5.context; }
    if (((token === import36.NG_VALIDATORS) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NG_VALIDATORS_56_6; }
    if (((token === import37.NG_VALUE_ACCESSOR) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NG_VALUE_ACCESSOR_56_7; }
    if (((token === import38.NgModel) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgModel_56_8.context; }
    if (((token === import39.NgControl) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgControl_56_9; }
    if (((token === import40.NgControlStatus) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgControlStatus_56_10.context; }
    if (((token === import20.TemplateRef) && (61 === requestNodeIndex))) { return this._TemplateRef_61_5; }
    if (((token === import21.NgIf) && (61 === requestNodeIndex))) { return this._NgIf_61_6.context; }
    if (((token === import42.RouterLink) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._RouterLink_71_3.context; }
    if (((token === import20.TemplateRef) && (74 === requestNodeIndex))) { return this._TemplateRef_74_5; }
    if (((token === import21.NgIf) && (74 === requestNodeIndex))) { return this._NgIf_74_6.context; }
    if (((token === import43.NgForm) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._NgForm_26_3.context; }
    if (((token === import44.ControlContainer) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._ControlContainer_26_4; }
    if (((token === import40.NgControlStatusGroup) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._NgControlStatusGroup_26_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = this.context.message;
    this._NgIf_12_6.check_ngIf(currVal_12_0_0,throwOnChange,false);
    this._NgIf_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    this._NgForm_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgControlStatusGroup_26_5.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_32_0_0:any = 'form-control';
    this._NgClass_32_3.check_klass(currVal_32_0_0,throwOnChange,false);
    const currVal_32_0_1:any = this._map_156((this._NgModel_32_8.context.errors && (this._NgModel_32_8.context.dirty || this._NgModel_32_8.context.touched)));
    this._NgClass_32_3.check_ngClass(currVal_32_0_1,throwOnChange,false);
    this._NgClass_32_3.ngDoCheck(this,this._el_32,throwOnChange);
    this._SelectControlValueAccessor_32_4.ngDoCheck(this,this._el_32,throwOnChange);
    const currVal_32_2_0:any = '';
    this._RequiredValidator_32_5.check_required(currVal_32_2_0,throwOnChange,false);
    this._RequiredValidator_32_5.ngDoCheck(this,this._el_32,throwOnChange);
    const currVal_32_3_0:any = 'docType';
    this._NgModel_32_8.check_name(currVal_32_3_0,throwOnChange,false);
    const currVal_32_3_1:any = this.context.user.documentType;
    this._NgModel_32_8.check_model(currVal_32_3_1,throwOnChange,false);
    this._NgModel_32_8.ngDoCheck(this,this._el_32,throwOnChange);
    this._NgControlStatus_32_10.ngDoCheck(this,this._el_32,throwOnChange);
    const currVal_34_0_0:any = this.context.documentTypes;
    this._NgFor_34_6.check_ngForOf(currVal_34_0_0,throwOnChange,false);
    this._NgFor_34_6.ngDoCheck(this,this._anchor_34,throwOnChange);
    const currVal_37_0_0:any = (this._NgModel_32_8.context.errors && (this._NgModel_32_8.context.dirty || this._NgModel_32_8.context.touched));
    this._NgIf_37_6.check_ngIf(currVal_37_0_0,throwOnChange,false);
    this._NgIf_37_6.ngDoCheck(this,this._anchor_37,throwOnChange);
    const currVal_42_0_0:any = 'form-control';
    this._NgClass_42_3.check_klass(currVal_42_0_0,throwOnChange,false);
    const currVal_42_0_1:any = this._map_157((this._NgModel_42_8.context.errors && (this._NgModel_49_8.context.dirty || this._NgModel_49_8.context.touched)));
    this._NgClass_42_3.check_ngClass(currVal_42_0_1,throwOnChange,false);
    this._NgClass_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    this._DefaultValueAccessor_42_4.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_2_0:any = '';
    this._RequiredValidator_42_5.check_required(currVal_42_2_0,throwOnChange,false);
    this._RequiredValidator_42_5.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_3_0:any = 'docId';
    this._NgModel_42_8.check_name(currVal_42_3_0,throwOnChange,false);
    const currVal_42_3_1:any = this.context.user.documentId;
    this._NgModel_42_8.check_model(currVal_42_3_1,throwOnChange,false);
    this._NgModel_42_8.ngDoCheck(this,this._el_42,throwOnChange);
    this._NgControlStatus_42_10.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_44_0_0:any = (this._NgModel_42_8.context.errors && (this._NgModel_42_8.context.dirty || this._NgModel_42_8.context.touched));
    this._NgIf_44_6.check_ngIf(currVal_44_0_0,throwOnChange,false);
    this._NgIf_44_6.ngDoCheck(this,this._anchor_44,throwOnChange);
    const currVal_49_0_0:any = 'form-control';
    this._NgClass_49_3.check_klass(currVal_49_0_0,throwOnChange,false);
    const currVal_49_0_1:any = this._map_158((this._NgModel_49_8.context.errors && (this._NgModel_49_8.context.dirty || this._NgModel_49_8.context.touched)));
    this._NgClass_49_3.check_ngClass(currVal_49_0_1,throwOnChange,false);
    this._NgClass_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    this._DefaultValueAccessor_49_4.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_2_0:any = '';
    this._RequiredValidator_49_5.check_required(currVal_49_2_0,throwOnChange,false);
    this._RequiredValidator_49_5.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_3_0:any = 'pwd';
    this._NgModel_49_8.check_name(currVal_49_3_0,throwOnChange,false);
    const currVal_49_3_1:any = this.context.user.password;
    this._NgModel_49_8.check_model(currVal_49_3_1,throwOnChange,false);
    this._NgModel_49_8.ngDoCheck(this,this._el_49,throwOnChange);
    this._NgControlStatus_49_10.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_51_0_0:any = (this._NgModel_49_8.context.errors && (this._NgModel_49_8.context.dirty || this._NgModel_49_8.context.touched));
    this._NgIf_51_6.check_ngIf(currVal_51_0_0,throwOnChange,false);
    this._NgIf_51_6.ngDoCheck(this,this._anchor_51,throwOnChange);
    const currVal_56_0_0:any = 'form-control';
    this._NgClass_56_3.check_klass(currVal_56_0_0,throwOnChange,false);
    const currVal_56_0_1:any = this._map_159((this._NgModel_56_8.context.errors && (this._NgModel_49_8.context.dirty || this._NgModel_49_8.context.touched)));
    this._NgClass_56_3.check_ngClass(currVal_56_0_1,throwOnChange,false);
    this._NgClass_56_3.ngDoCheck(this,this._el_56,throwOnChange);
    this._SelectControlValueAccessor_56_4.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_56_2_0:any = '';
    this._RequiredValidator_56_5.check_required(currVal_56_2_0,throwOnChange,false);
    this._RequiredValidator_56_5.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_56_3_0:any = 'userType';
    this._NgModel_56_8.check_name(currVal_56_3_0,throwOnChange,false);
    const currVal_56_3_1:any = this.context.user.userType;
    this._NgModel_56_8.check_model(currVal_56_3_1,throwOnChange,false);
    this._NgModel_56_8.ngDoCheck(this,this._el_56,throwOnChange);
    this._NgControlStatus_56_10.ngDoCheck(this,this._el_56,throwOnChange);
    const currVal_58_0_0:any = this.context.userTypes;
    this._NgFor_58_6.check_ngForOf(currVal_58_0_0,throwOnChange,false);
    this._NgFor_58_6.ngDoCheck(this,this._anchor_58,throwOnChange);
    const currVal_61_0_0:any = (this._NgModel_56_8.context.errors && (this._NgModel_56_8.context.dirty || this._NgModel_56_8.context.touched));
    this._NgIf_61_6.check_ngIf(currVal_61_0_0,throwOnChange,false);
    this._NgIf_61_6.ngDoCheck(this,this._anchor_61,throwOnChange);
    const currVal_71_0_0:any = this._arr_161('/forgot');
    this._RouterLink_71_3.check_routerLink(currVal_71_0_0,throwOnChange,false);
    this._RouterLink_71_3.ngDoCheck(this,this._el_71,throwOnChange);
    const currVal_74_0_0:any = this.context.isLoading;
    this._NgIf_74_6.check_ngIf(currVal_74_0_0,throwOnChange,false);
    this._NgIf_74_6.ngDoCheck(this,this._anchor_74,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_34.detectChangesInNestedViews(throwOnChange);
    this._vc_37.detectChangesInNestedViews(throwOnChange);
    this._vc_44.detectChangesInNestedViews(throwOnChange);
    this._vc_51.detectChangesInNestedViews(throwOnChange);
    this._vc_58.detectChangesInNestedViews(throwOnChange);
    this._vc_61.detectChangesInNestedViews(throwOnChange);
    this._vc_74.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_26_5.checkHost(this,this,this._el_26,throwOnChange);
    this._RequiredValidator_32_5.checkHost(this,this,this._el_32,throwOnChange);
    this._NgControlStatus_32_10.checkHost(this,this,this._el_32,throwOnChange);
    this._RequiredValidator_42_5.checkHost(this,this,this._el_42,throwOnChange);
    this._NgControlStatus_42_10.checkHost(this,this,this._el_42,throwOnChange);
    this._RequiredValidator_49_5.checkHost(this,this,this._el_49,throwOnChange);
    this._NgControlStatus_49_10.checkHost(this,this,this._el_49,throwOnChange);
    this._RequiredValidator_56_5.checkHost(this,this,this._el_56,throwOnChange);
    this._NgControlStatus_56_10.checkHost(this,this,this._el_56,throwOnChange);
    const currVal_160:boolean = !this._NgForm_26_3.context.valid;
    if (import3.checkBinding(throwOnChange,this._expr_160,currVal_160)) {
      this.renderer.setElementProperty(this._el_68,'disabled',currVal_160);
      this._expr_160 = currVal_160;
    }
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
    this._vc_34.destroyNestedViews();
    this._vc_37.destroyNestedViews();
    this._vc_44.destroyNestedViews();
    this._vc_51.destroyNestedViews();
    this._vc_58.destroyNestedViews();
    this._vc_61.destroyNestedViews();
    this._vc_74.destroyNestedViews();
    this._NgModel_32_8.ngOnDestroy();
    this._NgModel_42_8.ngOnDestroy();
    this._NgModel_49_8.ngOnDestroy();
    this._NgModel_56_8.ngOnDestroy();
    this._NgForm_26_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_LoginComponent1(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 34)) { return new View_LoginComponent2(this.viewUtils,this,34,this._anchor_34,this._vc_34); }
    if ((nodeIndex == 37)) { return new View_LoginComponent3(this.viewUtils,this,37,this._anchor_37,this._vc_37); }
    if ((nodeIndex == 44)) { return new View_LoginComponent5(this.viewUtils,this,44,this._anchor_44,this._vc_44); }
    if ((nodeIndex == 51)) { return new View_LoginComponent7(this.viewUtils,this,51,this._anchor_51,this._vc_51); }
    if ((nodeIndex == 58)) { return new View_LoginComponent9(this.viewUtils,this,58,this._anchor_58,this._vc_58); }
    if ((nodeIndex == 61)) { return new View_LoginComponent10(this.viewUtils,this,61,this._anchor_61,this._vc_61); }
    if ((nodeIndex == 74)) { return new View_LoginComponent12(this.viewUtils,this,74,this._anchor_74,this._vc_74); }
    return (null as any);
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_26_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>(this._NgForm_26_3.context.form.valid && this.context.login())) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_32(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_32_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.user.documentType = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_42_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.user.documentId = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_49(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_49_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.user.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_56(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_56_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.user.userType = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_71(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_71_3.handleEvent(eventName,$event) && result);
    return result;
  }
}