/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../angularApp/app/audit/components/audit.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../angularApp/app/app.constants';
import * as import9 from '../../../../../angularApp/app/core/services/audit.service';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/router/src/router_state';
import * as import12 from '@angular/common/src/location/location';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '@angular/core/src/change_detection/change_detection_util';
import * as import15 from '@angular/core/src/security';
import * as import16 from '../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import18 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/common/src/directives/ng_class';
import * as import21 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import25 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import26 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import27 from '@angular/common/src/directives/ng_if';
import * as import28 from '@angular/forms/src/directives/ng_form';
import * as import29 from '@angular/forms/src/directives/control_container';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_AuditComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AuditComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.AuditComponent(p0,p1,p2,p3,p4);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AuditComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AuditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AuditComponent>;
  _AuditComponent_0_3:Wrapper_AuditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AuditComponent_Host0,renderType_AuditComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'audit-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AuditComponent0(this.viewUtils,this,0,this._el_0);
    this._AuditComponent_0_3 = new Wrapper_AuditComponent(this.injectorGet(import8.Configuration,this.parentIndex),this.injectorGet(import9.AuditService,this.parentIndex),this.injectorGet(import10.Router,this.parentIndex),this.injectorGet(import11.ActivatedRoute,this.parentIndex),this.injectorGet(import12.Location,this.parentIndex));
    this.compView_0.create(this._AuditComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AuditComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AuditComponent) && (0 === requestNodeIndex))) { return this._AuditComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AuditComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AuditComponentNgFactory:import7.ComponentFactory<import0.AuditComponent> = new import7.ComponentFactory<import0.AuditComponent>('audit-component',View_AuditComponent_Host0,import0.AuditComponent);
const styles_AuditComponent:any[] = ([] as any[]);
class View_AuditComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_AuditComponent1,renderType_AuditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.context.message;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AuditComponent2 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_AuditComponent2,renderType_AuditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'height','24','src','/assets/spin.svg','width','24'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AuditComponent3 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import16.Wrapper_NgClass;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _map_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_AuditComponent3,renderType_AuditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_6 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
    this._expr_7 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_0_3 = new import16.Wrapper_NgClass(this.parentView.parentView.injectorGet(import17.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import18.KeyValueDiffers,this.parentView.parentIndex),new import19.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','javascript:void(0);'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this._map_6((this.parentView.context.grid.pageSize == this.context.$implicit));
    this._NgClass_0_3.check_ngClass(currVal_0_0_0,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_7:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_3,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.grid.setPageSize(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AuditComponent4 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import16.Wrapper_NgClass;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _map_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_AuditComponent4,renderType_AuditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_6 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
    this._expr_7 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_0_3 = new import16.Wrapper_NgClass(this.parentView.parentView.injectorGet(import17.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import18.KeyValueDiffers,this.parentView.parentIndex),new import19.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','javascript:void(0);'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this._map_6((this.parentView.context.grid.currentPage == this.context.$implicit));
    this._NgClass_0_3.check_ngClass(currVal_0_0_0,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_7:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_3,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.grid.setPage(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AuditComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_AuditComponent5,renderType_AuditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'th',new import3.InlineArray2(2,'class','colHeader'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'class','colHeader'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.grid.sort(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AuditComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_AuditComponent7,renderType_AuditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'td',new import3.InlineArray2(2,'class','colText'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit[this.context.$implicit.id],'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_AuditComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import13.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import21.Wrapper_NgFor;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_AuditComponent6,renderType_AuditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import13.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import22.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import21.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.injectorGet(import17.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'                                \n                            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import23.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.grid.columns;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_AuditComponent7(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
var renderType_AuditComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AuditComponent,{});
export class View_AuditComponent0 extends import1.AppView<import0.AuditComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import13.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import24.Wrapper_NgIf;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _NgForm_23_3:import25.Wrapper_NgForm;
  _ControlContainer_23_4:any;
  _NgControlStatusGroup_23_5:import26.Wrapper_NgControlStatusGroup;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _vc_31:import13.ViewContainer;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import24.Wrapper_NgIf;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _anchor_54:any;
  /*private*/ _vc_54:import13.ViewContainer;
  _TemplateRef_54_5:any;
  _NgFor_54_6:import21.Wrapper_NgFor;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _NgClass_68_3:import16.Wrapper_NgClass;
  _text_69:any;
  _el_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _anchor_74:any;
  /*private*/ _vc_74:import13.ViewContainer;
  _TemplateRef_74_5:any;
  _NgFor_74_6:import21.Wrapper_NgFor;
  _text_75:any;
  _el_76:any;
  _NgClass_76_3:import16.Wrapper_NgClass;
  _text_77:any;
  _el_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _anchor_93:any;
  /*private*/ _vc_93:import13.ViewContainer;
  _TemplateRef_93_5:any;
  _NgFor_93_6:import21.Wrapper_NgFor;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _anchor_99:any;
  /*private*/ _vc_99:import13.ViewContainer;
  _TemplateRef_99_5:any;
  _NgFor_99_6:import21.Wrapper_NgFor;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  /*private*/ _expr_130:any;
  /*private*/ _expr_131:any;
  _map_132:any;
  _map_133:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AuditComponent0,renderType_AuditComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_130 = import14.UNINITIALIZED;
    this._expr_131 = import14.UNINITIALIZED;
    this._map_132 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {disabled: p0};
    });
    this._map_133 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {disabled: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','width:100%;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'span',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Auditoría',(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._vc_14 = new import13.ViewContainer(14,12,this,this._anchor_14);
    this._TemplateRef_14_5 = new import22.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import24.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'form',new import3.InlineArray2(2,'class','form-inline'),(null as any));
    this._NgForm_23_3 = new import25.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_23_4 = this._NgForm_23_3.context;
    this._NgControlStatusGroup_23_5 = new import26.Wrapper_NgControlStatusGroup(this._ControlContainer_23_4);
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'div',new import3.InlineArray4(4,'class','form-group','style','margin-right: 10px'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'ul',new import3.InlineArray4(4,'class','pagination pagination-sm','style','margin: 0px'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                            ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n                                ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_29,(null as any));
    this._vc_31 = new import13.ViewContainer(31,29,this,this._anchor_31);
    this._TemplateRef_31_5 = new import22.TemplateRef_(this,31,this._anchor_31);
    this._NgIf_31_6 = new import24.Wrapper_NgIf(this._vc_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText(this._el_29,'\n                            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n                            ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_27,'li',new import3.InlineArray2(2,'class','disabled'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n                                ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'a',new import3.InlineArray2(2,'href','javascript:void(0);'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Total: ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_34,'\n                            ',(null as any));
    this._text_41 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._text_42 = this.renderer.createText(this._el_25,'\n                    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_23,'div',new import3.InlineArray4(4,'class','form-group','style','margin-right: 10px'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n                        ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_44,'ul',new import3.InlineArray4(4,'class','pagination pagination-sm','style','margin: 0px'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                            ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'li',new import3.InlineArray2(2,'class','disabled'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n                                ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'a',new import3.InlineArray2(2,'href','javascript:void(0);'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'Paginación:',(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n                            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_46,'\n                            ',(null as any));
    this._anchor_54 = this.renderer.createTemplateAnchor(this._el_46,(null as any));
    this._vc_54 = new import13.ViewContainer(54,46,this,this._anchor_54);
    this._TemplateRef_54_5 = new import22.TemplateRef_(this,54,this._anchor_54);
    this._NgFor_54_6 = new import21.Wrapper_NgFor(this._vc_54.vcRef,this._TemplateRef_54_5,this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.ref);
    this._text_55 = this.renderer.createText(this._el_46,'\n                        ',(null as any));
    this._text_56 = this.renderer.createText(this._el_44,'\n                    ',(null as any));
    this._text_57 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_23,'div',new import3.InlineArray4(4,'class','form-group','style','margin-right: 10px'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'\n                        ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_58,'ul',new import3.InlineArray4(4,'class','pagination pagination-sm','style','margin: 0px'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'\n                            ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_60,'li',new import3.InlineArray2(2,'class','disabled'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n                                ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_62,'a',new import3.InlineArray2(2,'href','javascript:void(0);'),(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'',(null as any));
    this._text_66 = this.renderer.createText(this._el_62,'\n                            ',(null as any));
    this._text_67 = this.renderer.createText(this._el_60,'                          \n                            ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_60,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_68_3 = new import16.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_68),this.renderer);
    this._text_69 = this.renderer.createText(this._el_68,'\n                                ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_68,'a',new import3.InlineArray2(2,'href','javascript:void(0);'),(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_70,'i',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-step-backward'),(null as any));
    this._text_72 = this.renderer.createText(this._el_68,'\n                            ',(null as any));
    this._text_73 = this.renderer.createText(this._el_60,'\n                            ',(null as any));
    this._anchor_74 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._vc_74 = new import13.ViewContainer(74,60,this,this._anchor_74);
    this._TemplateRef_74_5 = new import22.TemplateRef_(this,74,this._anchor_74);
    this._NgFor_74_6 = new import21.Wrapper_NgFor(this._vc_74.vcRef,this._TemplateRef_74_5,this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.ref);
    this._text_75 = this.renderer.createText(this._el_60,'\n                            ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_60,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_76_3 = new import16.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_76),this.renderer);
    this._text_77 = this.renderer.createText(this._el_76,'\n                                ',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,this._el_76,'a',new import3.InlineArray2(2,'href','javascript:void(0);'),(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_78,'i',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-step-forward'),(null as any));
    this._text_80 = this.renderer.createText(this._el_76,'\n                            ',(null as any));
    this._text_81 = this.renderer.createText(this._el_60,'\n                        ',(null as any));
    this._text_82 = this.renderer.createText(this._el_58,'                        \n                    ',(null as any));
    this._text_83 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._text_84 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','table-responsive'),(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'\n                    ',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_85,'table',new import3.InlineArray2(2,'class','table table-hover table-striped table-bordered table-condensed'),(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'\n                        ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_87,'thead',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'\n                            ',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_89,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'\n                                ',(null as any));
    this._anchor_93 = this.renderer.createTemplateAnchor(this._el_91,(null as any));
    this._vc_93 = new import13.ViewContainer(93,91,this,this._anchor_93);
    this._TemplateRef_93_5 = new import22.TemplateRef_(this,93,this._anchor_93);
    this._NgFor_93_6 = new import21.Wrapper_NgFor(this._vc_93.vcRef,this._TemplateRef_93_5,this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.ref);
    this._text_94 = this.renderer.createText(this._el_91,'\n                            ',(null as any));
    this._text_95 = this.renderer.createText(this._el_89,'\n                        ',(null as any));
    this._text_96 = this.renderer.createText(this._el_87,'\n                        ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_87,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'\n                            ',(null as any));
    this._anchor_99 = this.renderer.createTemplateAnchor(this._el_97,(null as any));
    this._vc_99 = new import13.ViewContainer(99,97,this,this._anchor_99);
    this._TemplateRef_99_5 = new import22.TemplateRef_(this,99,this._anchor_99);
    this._NgFor_99_6 = new import21.Wrapper_NgFor(this._vc_99.vcRef,this._TemplateRef_99_5,this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.ref);
    this._text_100 = this.renderer.createText(this._el_97,'\n                        ',(null as any));
    this._text_101 = this.renderer.createText(this._el_87,'\n                    ',(null as any));
    this._text_102 = this.renderer.createText(this._el_85,'\n                ',(null as any));
    this._text_103 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_104 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_105 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_106 = this.renderer.createText(this._el_0,'   \n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_70,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_70));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_78,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_78));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._anchor_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._anchor_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._anchor_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._anchor_99,
      this._text_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105,
      this._text_106
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import27.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import22.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import27.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6.context; }
    if (((token === import22.TemplateRef) && (54 === requestNodeIndex))) { return this._TemplateRef_54_5; }
    if (((token === import23.NgFor) && (54 === requestNodeIndex))) { return this._NgFor_54_6.context; }
    if (((token === import20.NgClass) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._NgClass_68_3.context; }
    if (((token === import22.TemplateRef) && (74 === requestNodeIndex))) { return this._TemplateRef_74_5; }
    if (((token === import23.NgFor) && (74 === requestNodeIndex))) { return this._NgFor_74_6.context; }
    if (((token === import20.NgClass) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._NgClass_76_3.context; }
    if (((token === import28.NgForm) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 83)))) { return this._NgForm_23_3.context; }
    if (((token === import29.ControlContainer) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 83)))) { return this._ControlContainer_23_4; }
    if (((token === import30.NgControlStatusGroup) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 83)))) { return this._NgControlStatusGroup_23_5.context; }
    if (((token === import22.TemplateRef) && (93 === requestNodeIndex))) { return this._TemplateRef_93_5; }
    if (((token === import23.NgFor) && (93 === requestNodeIndex))) { return this._NgFor_93_6.context; }
    if (((token === import22.TemplateRef) && (99 === requestNodeIndex))) { return this._TemplateRef_99_5; }
    if (((token === import23.NgFor) && (99 === requestNodeIndex))) { return this._NgFor_99_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_14_0_0:any = this.context.message;
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    this._NgForm_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatusGroup_23_5.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_31_0_0:any = this.context.isLoading;
    this._NgIf_31_6.check_ngIf(currVal_31_0_0,throwOnChange,false);
    this._NgIf_31_6.ngDoCheck(this,this._anchor_31,throwOnChange);
    const currVal_54_0_0:any = this.context.grid.pageSizes;
    this._NgFor_54_6.check_ngForOf(currVal_54_0_0,throwOnChange,false);
    this._NgFor_54_6.ngDoCheck(this,this._anchor_54,throwOnChange);
    const currVal_68_0_0:any = this._map_132(((this.context.grid.currentPage == 1) || (this.context.grid.rowsCount == 0)));
    this._NgClass_68_3.check_ngClass(currVal_68_0_0,throwOnChange,false);
    this._NgClass_68_3.ngDoCheck(this,this._el_68,throwOnChange);
    const currVal_74_0_0:any = this.context.grid.pagesIndex;
    this._NgFor_74_6.check_ngForOf(currVal_74_0_0,throwOnChange,false);
    this._NgFor_74_6.ngDoCheck(this,this._anchor_74,throwOnChange);
    const currVal_76_0_0:any = this._map_133(((this.context.grid.currentPage == this.context.grid.rowsCount) || (this.context.grid.rowsCount == 0)));
    this._NgClass_76_3.check_ngClass(currVal_76_0_0,throwOnChange,false);
    this._NgClass_76_3.ngDoCheck(this,this._el_76,throwOnChange);
    const currVal_93_0_0:any = this.context.grid.columns;
    this._NgFor_93_6.check_ngForOf(currVal_93_0_0,throwOnChange,false);
    this._NgFor_93_6.ngDoCheck(this,this._anchor_93,throwOnChange);
    const currVal_99_0_0:any = this.context.grid.rows;
    this._NgFor_99_6.check_ngForOf(currVal_99_0_0,throwOnChange,false);
    this._NgFor_99_6.ngDoCheck(this,this._anchor_99,throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_31.detectChangesInNestedViews(throwOnChange);
    this._vc_54.detectChangesInNestedViews(throwOnChange);
    this._vc_74.detectChangesInNestedViews(throwOnChange);
    this._vc_93.detectChangesInNestedViews(throwOnChange);
    this._vc_99.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_23_5.checkHost(this,this,this._el_23,throwOnChange);
    const currVal_130:any = import3.inlineInterpolate(1,'',this.context.totalRows,'');
    if (import3.checkBinding(throwOnChange,this._expr_130,currVal_130)) {
      this.renderer.setText(this._text_39,currVal_130);
      this._expr_130 = currVal_130;
    }
    const currVal_131:any = import3.inlineInterpolate(2,'Página ',this.context.grid.currentPage,' de ',this.context.grid.rowsCount,'');
    if (import3.checkBinding(throwOnChange,this._expr_131,currVal_131)) {
      this.renderer.setText(this._text_65,currVal_131);
      this._expr_131 = currVal_131;
    }
  }
  destroyInternal():void {
    this._vc_14.destroyNestedViews();
    this._vc_31.destroyNestedViews();
    this._vc_54.destroyNestedViews();
    this._vc_74.destroyNestedViews();
    this._vc_93.destroyNestedViews();
    this._vc_99.destroyNestedViews();
    this._NgForm_23_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 14)) { return new View_AuditComponent1(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 31)) { return new View_AuditComponent2(this.viewUtils,this,31,this._anchor_31,this._vc_31); }
    if ((nodeIndex == 54)) { return new View_AuditComponent3(this.viewUtils,this,54,this._anchor_54,this._vc_54); }
    if ((nodeIndex == 74)) { return new View_AuditComponent4(this.viewUtils,this,74,this._anchor_74,this._vc_74); }
    if ((nodeIndex == 93)) { return new View_AuditComponent5(this.viewUtils,this,93,this._anchor_93,this._vc_93); }
    if ((nodeIndex == 99)) { return new View_AuditComponent6(this.viewUtils,this,99,this._anchor_99,this._vc_99); }
    return (null as any);
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_23_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_70(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.grid.prevPage()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_78(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.grid.nextPage()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}