//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabOnline.Business.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MessageTexts() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabOnline.Business.Resources.MessageTexts", typeof(MessageTexts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contraseña actual o confirmación incorrecta.
        /// </summary>
        public static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirmación de correo.
        /// </summary>
        public static string EmailConfirm {
            get {
                return ResourceManager.GetString("EmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to La cuenta no tiene solicitud de confirmación pendiente.
        /// </summary>
        public static string EmailConfirmFailed {
            get {
                return ResourceManager.GetString("EmailConfirmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Olvido de contraseña.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generar reporte de la order.
        /// </summary>
        public static string GeneratePdf {
            get {
                return ResourceManager.GetString("GeneratePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Operación con tipo de dato incorrecto.
        /// </summary>
        public static string IncorrectDataType {
            get {
                return ResourceManager.GetString("IncorrectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Usuario o contraseña incorrectos.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reestablecer contraseña.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to La cuenta no tiene solicitud de restablecer contraseña pendiente.
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Proceso exitoso.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Creación de usuario.
        /// </summary>
        public static string UserCreation {
            get {
                return ResourceManager.GetString("UserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Borrar usuario.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to El usuario &apos;{0}&apos; actualmente ya existe.
        /// </summary>
        public static string UserDuplicated {
            get {
                return ResourceManager.GetString("UserDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Administración usuario.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Actualización de usuario.
        /// </summary>
        public static string UserUpdate {
            get {
                return ResourceManager.GetString("UserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Correo de bienvenida.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
