/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../angularApp/app/users/user.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from '@angular/http/src/http_module';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import9 from '@angular/http/src/backends/browser_xhr';
import * as import10 from '@angular/http/src/base_response_options';
import * as import11 from '@angular/http/src/backends/xhr_backend';
import * as import12 from '@angular/http/src/base_request_options';
import * as import13 from '@angular/core/src/di/injector';
import * as import14 from './components/user.component.ngfactory';
import * as import15 from './components/change.component.ngfactory';
import * as import16 from './components/forgot.component.ngfactory';
import * as import17 from './components/reset.component.ngfactory';
import * as import18 from '@angular/core/src/i18n/tokens';
import * as import19 from '../../../../angularApp/app/users/components/user.component';
import * as import20 from '../../../../angularApp/app/users/components/change.component';
import * as import21 from '../../../../angularApp/app/users/components/forgot.component';
import * as import22 from '../../../../angularApp/app/users/components/reset.component';
import * as import23 from '@angular/http/src/interfaces';
import * as import24 from '@angular/http/src/http';
import * as import25 from '@angular/router/src/router_config_loader';
class UserModuleInjector extends import0.NgModuleInjector<import1.UserModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _HttpModule_4:import6.HttpModule;
  _UserModule_5:import1.UserModule;
  __NgLocalization_6:import7.NgLocaleLocalization;
  __RadioControlRegistry_7:import8.RadioControlRegistry;
  __BrowserXhr_8:import9.BrowserXhr;
  __ResponseOptions_9:import10.BaseResponseOptions;
  __XSRFStrategy_10:any;
  __XHRBackend_11:import11.XHRBackend;
  __RequestOptions_12:import12.BaseRequestOptions;
  __Http_13:any;
  __ROUTES_14:any[];
  constructor(parent:import13.Injector) {
    super(parent,[
      import14.UserComponentNgFactory,
      import15.ChangePasswordComponentNgFactory,
      import16.ForgotPasswordComponentNgFactory,
      import17.ResetPasswordComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_6():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import7.NgLocaleLocalization(this.parent.get(import18.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  get _RadioControlRegistry_7():import8.RadioControlRegistry {
    if ((this.__RadioControlRegistry_7 == null)) { (this.__RadioControlRegistry_7 = new import8.RadioControlRegistry()); }
    return this.__RadioControlRegistry_7;
  }
  get _BrowserXhr_8():import9.BrowserXhr {
    if ((this.__BrowserXhr_8 == null)) { (this.__BrowserXhr_8 = new import9.BrowserXhr()); }
    return this.__BrowserXhr_8;
  }
  get _ResponseOptions_9():import10.BaseResponseOptions {
    if ((this.__ResponseOptions_9 == null)) { (this.__ResponseOptions_9 = new import10.BaseResponseOptions()); }
    return this.__ResponseOptions_9;
  }
  get _XSRFStrategy_10():any {
    if ((this.__XSRFStrategy_10 == null)) { (this.__XSRFStrategy_10 = import6._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_10;
  }
  get _XHRBackend_11():import11.XHRBackend {
    if ((this.__XHRBackend_11 == null)) { (this.__XHRBackend_11 = new import11.XHRBackend(this._BrowserXhr_8,this._ResponseOptions_9,this._XSRFStrategy_10)); }
    return this.__XHRBackend_11;
  }
  get _RequestOptions_12():import12.BaseRequestOptions {
    if ((this.__RequestOptions_12 == null)) { (this.__RequestOptions_12 = new import12.BaseRequestOptions()); }
    return this.__RequestOptions_12;
  }
  get _Http_13():any {
    if ((this.__Http_13 == null)) { (this.__Http_13 = import6.httpFactory(this._XHRBackend_11,this._RequestOptions_12)); }
    return this.__Http_13;
  }
  get _ROUTES_14():any[] {
      if ((this.__ROUTES_14 == null)) { (this.__ROUTES_14 = [[
        {
          path: '',
          component: import19.UserComponent
        }
        ,
        {
          path: 'changepsw',
          component: import20.ChangePasswordComponent
        }
        ,
        {
          path: 'forgot',
          component: import21.ForgotPasswordComponent
        }
        ,
        {
          path: 'resetpwd/:id',
          component: import22.ResetPasswordComponent
        }

      ]
    ]); }
    return this.__ROUTES_14;
  }
  createInternal():import1.UserModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._HttpModule_4 = new import6.HttpModule();
    this._UserModule_5 = new import1.UserModule();
    return this._UserModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import6.HttpModule)) { return this._HttpModule_4; }
    if ((token === import1.UserModule)) { return this._UserModule_5; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import8.RadioControlRegistry)) { return this._RadioControlRegistry_7; }
    if ((token === import9.BrowserXhr)) { return this._BrowserXhr_8; }
    if ((token === import10.ResponseOptions)) { return this._ResponseOptions_9; }
    if ((token === import23.XSRFStrategy)) { return this._XSRFStrategy_10; }
    if ((token === import11.XHRBackend)) { return this._XHRBackend_11; }
    if ((token === import12.RequestOptions)) { return this._RequestOptions_12; }
    if ((token === import24.Http)) { return this._Http_13; }
    if ((token === import25.ROUTES)) { return this._ROUTES_14; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const UserModuleNgFactory:import0.NgModuleFactory<import1.UserModule> = new import0.NgModuleFactory(UserModuleInjector,import1.UserModule);