/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../angularApp/app/users/components/change.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../angularApp/app/app.constants';
import * as import9 from '../../../../../angularApp/app/core/services/account.service';
import * as import10 from '@angular/router/src/router';
import * as import11 from '../../../../../angularApp/app/core/services/auth.service';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '@angular/core/src/security';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import18 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import19 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import21 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/router/src/router_state';
import * as import25 from '@angular/common/src/location/location_strategy';
import * as import26 from '@angular/forms/src/directives/default_value_accessor';
import * as import27 from '@angular/forms/src/directives/validators';
import * as import28 from '@angular/forms/src/validators';
import * as import29 from '@angular/forms/src/directives/control_value_accessor';
import * as import30 from '@angular/forms/src/directives/ng_model';
import * as import31 from '@angular/forms/src/directives/ng_control';
import * as import32 from '@angular/forms/src/directives/ng_control_status';
import * as import33 from '@angular/common/src/directives/ng_if';
import * as import34 from '@angular/router/src/directives/router_link';
import * as import35 from '@angular/forms/src/directives/ng_form';
import * as import36 from '@angular/forms/src/directives/control_container';
export class Wrapper_ChangePasswordComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ChangePasswordComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.ChangePasswordComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ChangePasswordComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ChangePasswordComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ChangePasswordComponent>;
  _ChangePasswordComponent_0_3:Wrapper_ChangePasswordComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChangePasswordComponent_Host0,renderType_ChangePasswordComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'change-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ChangePasswordComponent0(this.viewUtils,this,0,this._el_0);
    this._ChangePasswordComponent_0_3 = new Wrapper_ChangePasswordComponent(this.injectorGet(import8.Configuration,this.parentIndex),this.injectorGet(import9.AccountService,this.parentIndex),this.injectorGet(import10.Router,this.parentIndex),this.injectorGet(import11.AuthService,this.parentIndex));
    this.compView_0.create(this._ChangePasswordComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ChangePasswordComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ChangePasswordComponent) && (0 === requestNodeIndex))) { return this._ChangePasswordComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ChangePasswordComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ChangePasswordComponentNgFactory:import7.ComponentFactory<import0.ChangePasswordComponent> = new import7.ComponentFactory<import0.ChangePasswordComponent>('change-component',View_ChangePasswordComponent_Host0,import0.ChangePasswordComponent);
const styles_ChangePasswordComponent:any[] = ([] as any[]);
class View_ChangePasswordComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ChangePasswordComponent1,renderType_ChangePasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.context.message;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ChangePasswordComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ChangePasswordComponent3,renderType_ChangePasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                                La contraseña es entre 4 y 20 caracteres.\n                                            ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ChangePasswordComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ChangePasswordComponent4,renderType_ChangePasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                                La contraseña es entre 4 y 20 caracteres.\n                                            ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ChangePasswordComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ChangePasswordComponent5,renderType_ChangePasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                                La confirmación de contraseña es incorrecta.\n                                            ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ChangePasswordComponent6 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ChangePasswordComponent6,renderType_ChangePasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'height','24','src','/assets/spin.svg','width','24'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ChangePasswordComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgForm_2_3:import15.Wrapper_NgForm;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import16.Wrapper_NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _DefaultValueAccessor_8_3:import17.Wrapper_DefaultValueAccessor;
  _RequiredValidator_8_4:import18.Wrapper_RequiredValidator;
  _MinLengthValidator_8_5:import18.Wrapper_MinLengthValidator;
  _MaxLengthValidator_8_6:import18.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_8_7:any[];
  _NG_VALUE_ACCESSOR_8_8:any[];
  _NgModel_8_9:import19.Wrapper_NgModel;
  _NgControl_8_10:any;
  _NgControlStatus_8_11:import16.Wrapper_NgControlStatus;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _vc_10:import12.ViewContainer;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import20.Wrapper_NgIf;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _DefaultValueAccessor_15_3:import17.Wrapper_DefaultValueAccessor;
  _RequiredValidator_15_4:import18.Wrapper_RequiredValidator;
  _MinLengthValidator_15_5:import18.Wrapper_MinLengthValidator;
  _MaxLengthValidator_15_6:import18.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_15_7:any[];
  _NG_VALUE_ACCESSOR_15_8:any[];
  _NgModel_15_9:import19.Wrapper_NgModel;
  _NgControl_15_10:any;
  _NgControlStatus_15_11:import16.Wrapper_NgControlStatus;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import12.ViewContainer;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import20.Wrapper_NgIf;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import17.Wrapper_DefaultValueAccessor;
  _RequiredValidator_22_4:import18.Wrapper_RequiredValidator;
  _MinLengthValidator_22_5:import18.Wrapper_MinLengthValidator;
  _MaxLengthValidator_22_6:import18.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_22_7:any[];
  _NG_VALUE_ACCESSOR_22_8:any[];
  _NgModel_22_9:import19.Wrapper_NgModel;
  _NgControl_22_10:any;
  _NgControlStatus_22_11:import16.Wrapper_NgControlStatus;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _vc_24:import12.ViewContainer;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import20.Wrapper_NgIf;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _RouterLinkWithHref_33_3:import21.Wrapper_RouterLinkWithHref;
  _text_34:any;
  _text_35:any;
  _anchor_36:any;
  /*private*/ _vc_36:import12.ViewContainer;
  _TemplateRef_36_5:any;
  _NgIf_36_6:import20.Wrapper_NgIf;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  /*private*/ _expr_83:any;
  _arr_84:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ChangePasswordComponent2,renderType_ChangePasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_83 = import13.UNINITIALIZED;
    this._arr_84 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray4(4,'novalidate','','role','form'),(null as any));
    this._NgForm_2_3 = new import15.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_2_4 = this._NgForm_2_3.context;
    this._NgControlStatusGroup_2_5 = new import16.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n                                ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                                    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                                    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'input',new import3.InlineArrayDynamic(20,'autocomplete','off','autofocus','','class','form-control','id','password','maxlength','20','minlength','4','name','currentpassword','placeholder','Contraseña actual','required','','type','password'),(null as any));
    this._DefaultValueAccessor_8_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_8));
    this._RequiredValidator_8_4 = new import18.Wrapper_RequiredValidator();
    this._MinLengthValidator_8_5 = new import18.Wrapper_MinLengthValidator();
    this._MaxLengthValidator_8_6 = new import18.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_8_7 = [
      this._RequiredValidator_8_4.context,
      this._MinLengthValidator_8_5.context,
      this._MaxLengthValidator_8_6.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_8_8 = [this._DefaultValueAccessor_8_3.context];
    this._NgModel_8_9 = new import19.Wrapper_NgModel(this._ControlContainer_2_4,this._NG_VALIDATORS_8_7,(null as any),this._NG_VALUE_ACCESSOR_8_8);
    this._NgControl_8_10 = this._NgModel_8_9.context;
    this._NgControlStatus_8_11 = new import16.Wrapper_NgControlStatus(this._NgControl_8_10);
    this._text_9 = this.renderer.createText(this._el_6,'\n                                        ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_10 = new import12.ViewContainer(10,6,this,this._anchor_10);
    this._TemplateRef_10_5 = new import23.TemplateRef_(this,10,this._anchor_10);
    this._NgIf_10_6 = new import20.Wrapper_NgIf(this._vc_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(this._el_6,'\n                                    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_4,'\n                                    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                                        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'input',new import3.InlineArrayDynamic(22,'autocomplete','off','class','form-control','id','password','maxlength','20','minlength','4','name','password','placeholder','Nueva contraseña','required','','reverse','true','type','password','validateEqual','confirmPassword'),(null as any));
    this._DefaultValueAccessor_15_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_15));
    this._RequiredValidator_15_4 = new import18.Wrapper_RequiredValidator();
    this._MinLengthValidator_15_5 = new import18.Wrapper_MinLengthValidator();
    this._MaxLengthValidator_15_6 = new import18.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_15_7 = [
      this._RequiredValidator_15_4.context,
      this._MinLengthValidator_15_5.context,
      this._MaxLengthValidator_15_6.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_15_8 = [this._DefaultValueAccessor_15_3.context];
    this._NgModel_15_9 = new import19.Wrapper_NgModel(this._ControlContainer_2_4,this._NG_VALIDATORS_15_7,(null as any),this._NG_VALUE_ACCESSOR_15_8);
    this._NgControl_15_10 = this._NgModel_15_9.context;
    this._NgControlStatus_15_11 = new import16.Wrapper_NgControlStatus(this._NgControl_15_10);
    this._text_16 = this.renderer.createText(this._el_13,'\n                                        ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._vc_17 = new import12.ViewContainer(17,13,this,this._anchor_17);
    this._TemplateRef_17_5 = new import23.TemplateRef_(this,17,this._anchor_17);
    this._NgIf_17_6 = new import20.Wrapper_NgIf(this._vc_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_13,'\n                                    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_4,'\n                                    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n                                        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'input',new import3.InlineArrayDynamic(20,'autocomplete','off','class','form-control','id','confirmPassword','maxlength','20','minlength','4','name','confirmPassword','placeholder','Confirmar contraseña','required','','type','password','validateEqual','password'),(null as any));
    this._DefaultValueAccessor_22_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_22));
    this._RequiredValidator_22_4 = new import18.Wrapper_RequiredValidator();
    this._MinLengthValidator_22_5 = new import18.Wrapper_MinLengthValidator();
    this._MaxLengthValidator_22_6 = new import18.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_22_7 = [
      this._RequiredValidator_22_4.context,
      this._MinLengthValidator_22_5.context,
      this._MaxLengthValidator_22_6.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_22_8 = [this._DefaultValueAccessor_22_3.context];
    this._NgModel_22_9 = new import19.Wrapper_NgModel(this._ControlContainer_2_4,this._NG_VALIDATORS_22_7,(null as any),this._NG_VALUE_ACCESSOR_22_8);
    this._NgControl_22_10 = this._NgModel_22_9.context;
    this._NgControlStatus_22_11 = new import16.Wrapper_NgControlStatus(this._NgControl_22_10);
    this._text_23 = this.renderer.createText(this._el_20,'\n                                        ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._vc_24 = new import12.ViewContainer(24,20,this,this._anchor_24);
    this._TemplateRef_24_5 = new import23.TemplateRef_(this,24,this._anchor_24);
    this._NgIf_24_6 = new import20.Wrapper_NgIf(this._vc_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_20,'\n                                    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_4,'                              \n                                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n                                ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                                    ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'button',new import3.InlineArray4(4,'class','btn btn-warning btn-sm','type','submit'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                                        Cambiar contraseña\n                                    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n                                    ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_28,'a',new import3.InlineArray2(2,'class','btn btn-cancel btn-sm'),(null as any));
    this._RouterLinkWithHref_33_3 = new import21.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import10.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import24.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import25.LocationStrategy,this.parentView.parentIndex));
    this._text_34 = this.renderer.createText(this._el_33,'Cancelar',(null as any));
    this._text_35 = this.renderer.createText(this._el_28,'\n                                    ',(null as any));
    this._anchor_36 = this.renderer.createTemplateAnchor(this._el_28,(null as any));
    this._vc_36 = new import12.ViewContainer(36,28,this,this._anchor_36);
    this._TemplateRef_36_5 = new import23.TemplateRef_(this,36,this._anchor_36);
    this._NgIf_36_6 = new import20.Wrapper_NgIf(this._vc_36.vcRef,this._TemplateRef_36_5);
    this._text_37 = this.renderer.createText(this._el_28,'\n                                ',(null as any));
    this._text_38 = this.renderer.createText(this._el_2,'\n                            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this._NgForm_2_3.subscribe(this,this.eventHandler(this.handleEvent_2),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_8));
    this._NgModel_8_9.subscribe(this,this.eventHandler(this.handleEvent_8),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_15));
    this._NgModel_15_9.subscribe(this,this.eventHandler(this.handleEvent_15),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_22,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_22));
    this._NgModel_22_9.subscribe(this,this.eventHandler(this.handleEvent_22),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_33));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._anchor_36,
      this._text_37,
      this._text_38,
      this._text_39
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.DefaultValueAccessor) && (8 === requestNodeIndex))) { return this._DefaultValueAccessor_8_3.context; }
    if (((token === import27.RequiredValidator) && (8 === requestNodeIndex))) { return this._RequiredValidator_8_4.context; }
    if (((token === import27.MinLengthValidator) && (8 === requestNodeIndex))) { return this._MinLengthValidator_8_5.context; }
    if (((token === import27.MaxLengthValidator) && (8 === requestNodeIndex))) { return this._MaxLengthValidator_8_6.context; }
    if (((token === import28.NG_VALIDATORS) && (8 === requestNodeIndex))) { return this._NG_VALIDATORS_8_7; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (8 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_8_8; }
    if (((token === import30.NgModel) && (8 === requestNodeIndex))) { return this._NgModel_8_9.context; }
    if (((token === import31.NgControl) && (8 === requestNodeIndex))) { return this._NgControl_8_10; }
    if (((token === import32.NgControlStatus) && (8 === requestNodeIndex))) { return this._NgControlStatus_8_11.context; }
    if (((token === import23.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import33.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6.context; }
    if (((token === import26.DefaultValueAccessor) && (15 === requestNodeIndex))) { return this._DefaultValueAccessor_15_3.context; }
    if (((token === import27.RequiredValidator) && (15 === requestNodeIndex))) { return this._RequiredValidator_15_4.context; }
    if (((token === import27.MinLengthValidator) && (15 === requestNodeIndex))) { return this._MinLengthValidator_15_5.context; }
    if (((token === import27.MaxLengthValidator) && (15 === requestNodeIndex))) { return this._MaxLengthValidator_15_6.context; }
    if (((token === import28.NG_VALIDATORS) && (15 === requestNodeIndex))) { return this._NG_VALIDATORS_15_7; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (15 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_15_8; }
    if (((token === import30.NgModel) && (15 === requestNodeIndex))) { return this._NgModel_15_9.context; }
    if (((token === import31.NgControl) && (15 === requestNodeIndex))) { return this._NgControl_15_10; }
    if (((token === import32.NgControlStatus) && (15 === requestNodeIndex))) { return this._NgControlStatus_15_11.context; }
    if (((token === import23.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import33.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6.context; }
    if (((token === import26.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3.context; }
    if (((token === import27.RequiredValidator) && (22 === requestNodeIndex))) { return this._RequiredValidator_22_4.context; }
    if (((token === import27.MinLengthValidator) && (22 === requestNodeIndex))) { return this._MinLengthValidator_22_5.context; }
    if (((token === import27.MaxLengthValidator) && (22 === requestNodeIndex))) { return this._MaxLengthValidator_22_6.context; }
    if (((token === import28.NG_VALIDATORS) && (22 === requestNodeIndex))) { return this._NG_VALIDATORS_22_7; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_8; }
    if (((token === import30.NgModel) && (22 === requestNodeIndex))) { return this._NgModel_22_9.context; }
    if (((token === import31.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_10; }
    if (((token === import32.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_11.context; }
    if (((token === import23.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import33.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6.context; }
    if (((token === import34.RouterLinkWithHref) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._RouterLinkWithHref_33_3.context; }
    if (((token === import23.TemplateRef) && (36 === requestNodeIndex))) { return this._TemplateRef_36_5; }
    if (((token === import33.NgIf) && (36 === requestNodeIndex))) { return this._NgIf_36_6.context; }
    if (((token === import35.NgForm) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgForm_2_3.context; }
    if (((token === import36.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ControlContainer_2_4; }
    if (((token === import32.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControlStatusGroup_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    this._DefaultValueAccessor_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_8_1_0:any = '';
    this._RequiredValidator_8_4.check_required(currVal_8_1_0,throwOnChange,false);
    this._RequiredValidator_8_4.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_8_2_0:any = '4';
    this._MinLengthValidator_8_5.check_minlength(currVal_8_2_0,throwOnChange,false);
    this._MinLengthValidator_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_8_3_0:any = '20';
    this._MaxLengthValidator_8_6.check_maxlength(currVal_8_3_0,throwOnChange,false);
    this._MaxLengthValidator_8_6.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_8_4_0:any = 'currentpassword';
    this._NgModel_8_9.check_name(currVal_8_4_0,throwOnChange,false);
    const currVal_8_4_1:any = this.parentView.context.user.currentpassword;
    this._NgModel_8_9.check_model(currVal_8_4_1,throwOnChange,false);
    this._NgModel_8_9.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgControlStatus_8_11.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_10_0_0:any = (this._NgModel_8_9.context.errors && (this._NgModel_8_9.context.dirty || this._NgModel_8_9.context.touched));
    this._NgIf_10_6.check_ngIf(currVal_10_0_0,throwOnChange,false);
    this._NgIf_10_6.ngDoCheck(this,this._anchor_10,throwOnChange);
    this._DefaultValueAccessor_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = '';
    this._RequiredValidator_15_4.check_required(currVal_15_1_0,throwOnChange,false);
    this._RequiredValidator_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_2_0:any = '4';
    this._MinLengthValidator_15_5.check_minlength(currVal_15_2_0,throwOnChange,false);
    this._MinLengthValidator_15_5.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_3_0:any = '20';
    this._MaxLengthValidator_15_6.check_maxlength(currVal_15_3_0,throwOnChange,false);
    this._MaxLengthValidator_15_6.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_4_0:any = 'password';
    this._NgModel_15_9.check_name(currVal_15_4_0,throwOnChange,false);
    const currVal_15_4_1:any = this.parentView.context.user.password;
    this._NgModel_15_9.check_model(currVal_15_4_1,throwOnChange,false);
    this._NgModel_15_9.ngDoCheck(this,this._el_15,throwOnChange);
    this._NgControlStatus_15_11.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_17_0_0:any = (this._NgModel_15_9.context.errors && (this._NgModel_15_9.context.dirty || this._NgModel_15_9.context.touched));
    this._NgIf_17_6.check_ngIf(currVal_17_0_0,throwOnChange,false);
    this._NgIf_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    this._DefaultValueAccessor_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_1_0:any = '';
    this._RequiredValidator_22_4.check_required(currVal_22_1_0,throwOnChange,false);
    this._RequiredValidator_22_4.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_2_0:any = '4';
    this._MinLengthValidator_22_5.check_minlength(currVal_22_2_0,throwOnChange,false);
    this._MinLengthValidator_22_5.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_3_0:any = '20';
    this._MaxLengthValidator_22_6.check_maxlength(currVal_22_3_0,throwOnChange,false);
    this._MaxLengthValidator_22_6.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_4_0:any = 'confirmPassword';
    this._NgModel_22_9.check_name(currVal_22_4_0,throwOnChange,false);
    const currVal_22_4_1:any = this.parentView.context.user.confirmPassword;
    this._NgModel_22_9.check_model(currVal_22_4_1,throwOnChange,false);
    this._NgModel_22_9.ngDoCheck(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_11.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_24_0_0:any = (this._NgModel_22_9.context.errors && (this._NgModel_22_9.context.dirty || this._NgModel_22_9.context.touched));
    this._NgIf_24_6.check_ngIf(currVal_24_0_0,throwOnChange,false);
    this._NgIf_24_6.ngDoCheck(this,this._anchor_24,throwOnChange);
    const currVal_33_0_0:any = this._arr_84('/home');
    this._RouterLinkWithHref_33_3.check_routerLink(currVal_33_0_0,throwOnChange,false);
    this._RouterLinkWithHref_33_3.ngDoCheck(this,this._el_33,throwOnChange);
    const currVal_36_0_0:any = this.parentView.context.isLoading;
    this._NgIf_36_6.check_ngIf(currVal_36_0_0,throwOnChange,false);
    this._NgIf_36_6.ngDoCheck(this,this._anchor_36,throwOnChange);
    this._vc_10.detectChangesInNestedViews(throwOnChange);
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    this._vc_24.detectChangesInNestedViews(throwOnChange);
    this._vc_36.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this,this._el_2,throwOnChange);
    this._RequiredValidator_8_4.checkHost(this,this,this._el_8,throwOnChange);
    this._MinLengthValidator_8_5.checkHost(this,this,this._el_8,throwOnChange);
    this._MaxLengthValidator_8_6.checkHost(this,this,this._el_8,throwOnChange);
    this._NgControlStatus_8_11.checkHost(this,this,this._el_8,throwOnChange);
    this._RequiredValidator_15_4.checkHost(this,this,this._el_15,throwOnChange);
    this._MinLengthValidator_15_5.checkHost(this,this,this._el_15,throwOnChange);
    this._MaxLengthValidator_15_6.checkHost(this,this,this._el_15,throwOnChange);
    this._NgControlStatus_15_11.checkHost(this,this,this._el_15,throwOnChange);
    this._RequiredValidator_22_4.checkHost(this,this,this._el_22,throwOnChange);
    this._MinLengthValidator_22_5.checkHost(this,this,this._el_22,throwOnChange);
    this._MaxLengthValidator_22_6.checkHost(this,this,this._el_22,throwOnChange);
    this._NgControlStatus_22_11.checkHost(this,this,this._el_22,throwOnChange);
    const currVal_83:any = (this.parentView.context.isLoading || this._NgForm_2_3.context.invalid);
    if (import3.checkBinding(throwOnChange,this._expr_83,currVal_83)) {
      this.renderer.setElementProperty(this._el_30,'disabled',currVal_83);
      this._expr_83 = currVal_83;
    }
    this._RouterLinkWithHref_33_3.checkHost(this,this,this._el_33,throwOnChange);
  }
  destroyInternal():void {
    this._vc_10.destroyNestedViews();
    this._vc_17.destroyNestedViews();
    this._vc_24.destroyNestedViews();
    this._vc_36.destroyNestedViews();
    this._NgModel_8_9.ngOnDestroy();
    this._NgModel_15_9.ngOnDestroy();
    this._NgModel_22_9.ngOnDestroy();
    this._RouterLinkWithHref_33_3.ngOnDestroy();
    this._NgForm_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 10)) { return new View_ChangePasswordComponent3(this.viewUtils,this,10,this._anchor_10,this._vc_10); }
    if ((nodeIndex == 17)) { return new View_ChangePasswordComponent4(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    if ((nodeIndex == 24)) { return new View_ChangePasswordComponent5(this.viewUtils,this,24,this._anchor_24,this._vc_24); }
    if ((nodeIndex == 36)) { return new View_ChangePasswordComponent6(this.viewUtils,this,36,this._anchor_36,this._vc_36); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_2_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>(this._NgForm_2_3.context.form.valid && this.parentView.context.change())) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_8_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.user.currentpassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_15_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.user.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_22_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.user.confirmPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_33_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ChangePasswordComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import21.Wrapper_RouterLinkWithHref;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _arr_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ChangePasswordComponent7,renderType_ChangePasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._arr_12 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                    La contraseña ha sido cambiada exitosamente.\n                                ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'a',new import3.InlineArray2(2,'class','btn btn-warning'),(null as any));
    this._RouterLinkWithHref_7_3 = new import21.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import10.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import24.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import25.LocationStrategy,this.parentView.parentIndex));
    this._text_8 = this.renderer.createText(this._el_7,'Regresar',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n                                ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7_0_0:any = this._arr_12('/home');
    this._RouterLinkWithHref_7_3.check_routerLink(currVal_7_0_0,throwOnChange,false);
    this._RouterLinkWithHref_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._RouterLinkWithHref_7_3.checkHost(this,this,this._el_7,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_7_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_ChangePasswordComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ChangePasswordComponent,{});
export class View_ChangePasswordComponent0 extends import1.AppView<import0.ChangePasswordComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import12.ViewContainer;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import20.Wrapper_NgIf;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _vc_26:import12.ViewContainer;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import20.Wrapper_NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _vc_28:import12.ViewContainer;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import20.Wrapper_NgIf;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChangePasswordComponent0,renderType_ChangePasswordComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','bgLogin'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row vertical-offset-100'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-4 col-md-offset-4'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'p',new import3.InlineArray2(2,'class','headerForm'),(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_12 = new import12.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import23.TemplateRef_(this,12,this._anchor_12);
    this._NgIf_12_6 = new import20.Wrapper_NgIf(this._vc_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'h3',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_19,'span',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Cambiar Contraseña',(null as any));
    this._text_22 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                        ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._vc_26 = new import12.ViewContainer(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import23.TemplateRef_(this,26,this._anchor_26);
    this._NgIf_26_6 = new import20.Wrapper_NgIf(this._vc_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_24,'\n                        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._vc_28 = new import12.ViewContainer(28,24,this,this._anchor_28);
    this._TemplateRef_28_5 = new import23.TemplateRef_(this,28,this._anchor_28);
    this._NgIf_28_6 = new import20.Wrapper_NgIf(this._vc_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_15,'                    \n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import33.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    if (((token === import23.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import33.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6.context; }
    if (((token === import23.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import33.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = this.context.message;
    this._NgIf_12_6.check_ngIf(currVal_12_0_0,throwOnChange,false);
    this._NgIf_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_26_0_0:boolean = !this.context.isSuccess;
    this._NgIf_26_6.check_ngIf(currVal_26_0_0,throwOnChange,false);
    this._NgIf_26_6.ngDoCheck(this,this._anchor_26,throwOnChange);
    const currVal_28_0_0:any = this.context.isSuccess;
    this._NgIf_28_6.check_ngIf(currVal_28_0_0,throwOnChange,false);
    this._NgIf_28_6.ngDoCheck(this,this._anchor_28,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_26.detectChangesInNestedViews(throwOnChange);
    this._vc_28.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
    this._vc_26.destroyNestedViews();
    this._vc_28.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_ChangePasswordComponent1(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 26)) { return new View_ChangePasswordComponent2(this.viewUtils,this,26,this._anchor_26,this._vc_26); }
    if ((nodeIndex == 28)) { return new View_ChangePasswordComponent7(this.viewUtils,this,28,this._anchor_28,this._vc_28); }
    return (null as any);
  }
}