/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../angularApp/app/users/components/forgot.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../angularApp/app/core/services/account.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../../../../angularApp/app/core/services/auth.service';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/core/src/security';
import * as import14 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import18 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import19 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import20 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import21 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import22 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/router/src/router_state';
import * as import25 from '@angular/common/src/location/location_strategy';
import * as import26 from '@angular/forms/src/directives/default_value_accessor';
import * as import27 from '@angular/forms/src/directives/validators';
import * as import28 from '@angular/forms/src/validators';
import * as import29 from '@angular/forms/src/directives/control_value_accessor';
import * as import30 from '@angular/forms/src/directives/ng_model';
import * as import31 from '@angular/forms/src/directives/ng_control';
import * as import32 from '@angular/forms/src/directives/ng_control_status';
import * as import33 from '@angular/router/src/directives/router_link';
import * as import34 from '@angular/forms/src/directives/ng_form';
import * as import35 from '@angular/forms/src/directives/control_container';
export class Wrapper_ForgotPasswordComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ForgotPasswordComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.ForgotPasswordComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ForgotPasswordComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ForgotPasswordComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ForgotPasswordComponent>;
  _ForgotPasswordComponent_0_3:Wrapper_ForgotPasswordComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ForgotPasswordComponent_Host0,renderType_ForgotPasswordComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'forgot-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ForgotPasswordComponent0(this.viewUtils,this,0,this._el_0);
    this._ForgotPasswordComponent_0_3 = new Wrapper_ForgotPasswordComponent(this.injectorGet(import8.AccountService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.AuthService,this.parentIndex));
    this.compView_0.create(this._ForgotPasswordComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ForgotPasswordComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ForgotPasswordComponent) && (0 === requestNodeIndex))) { return this._ForgotPasswordComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ForgotPasswordComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ForgotPasswordComponentNgFactory:import7.ComponentFactory<import0.ForgotPasswordComponent> = new import7.ComponentFactory<import0.ForgotPasswordComponent>('forgot-component',View_ForgotPasswordComponent_Host0,import0.ForgotPasswordComponent);
const styles_ForgotPasswordComponent:any[] = ([] as any[]);
class View_ForgotPasswordComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ForgotPasswordComponent1,renderType_ForgotPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.context.message;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ForgotPasswordComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ForgotPasswordComponent4,renderType_ForgotPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                                El correo electrónico es requerido.\n                                            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ForgotPasswordComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import14.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ForgotPasswordComponent3,renderType_ForgotPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import15.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import14.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = ((<View_ForgotPasswordComponent2>this.parentView)._NgModel_11_8.context.hasError('required') || (<View_ForgotPasswordComponent2>this.parentView)._NgModel_11_8.context.hasError('pattern'));
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_ForgotPasswordComponent4(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_ForgotPasswordComponent5 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ForgotPasswordComponent5,renderType_ForgotPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'height','24','src','/assets/spin.svg','width','24'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ForgotPasswordComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _NgForm_5_3:import17.Wrapper_NgForm;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import18.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _DefaultValueAccessor_11_3:import19.Wrapper_DefaultValueAccessor;
  _RequiredValidator_11_4:import20.Wrapper_RequiredValidator;
  _PatternValidator_11_5:import20.Wrapper_PatternValidator;
  _NG_VALIDATORS_11_6:any[];
  _NG_VALUE_ACCESSOR_11_7:any[];
  _NgModel_11_8:import21.Wrapper_NgModel;
  _NgControl_11_9:any;
  _NgControlStatus_11_10:import18.Wrapper_NgControlStatus;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import11.ViewContainer;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import14.Wrapper_NgIf;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _RouterLinkWithHref_21_3:import22.Wrapper_RouterLinkWithHref;
  _text_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _vc_24:import11.ViewContainer;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import14.Wrapper_NgIf;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  /*private*/ _expr_47:any;
  _arr_48:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ForgotPasswordComponent2,renderType_ForgotPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_47 = import12.UNINITIALIZED;
    this._arr_48 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                Ingrese el correo electrónico que tienes registrado y recibirás \n                                un mensaje con instrucciones para cambiar tu contraseña.\n                            ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray4(4,'novalidate','','role','form'),(null as any));
    this._NgForm_5_3 = new import17.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_5_4 = this._NgForm_5_3.context;
    this._NgControlStatusGroup_5_5 = new import18.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n                                ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'fieldset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                                    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                                        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'input',new import3.InlineArrayDynamic(18,'autocomplete','off','autofocus','','class','form-control','id','email','name','email','pattern','^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$','placeholder','Dirección de correo','required','','type','email'),(null as any));
    this._DefaultValueAccessor_11_3 = new import19.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_11));
    this._RequiredValidator_11_4 = new import20.Wrapper_RequiredValidator();
    this._PatternValidator_11_5 = new import20.Wrapper_PatternValidator();
    this._NG_VALIDATORS_11_6 = [
      this._RequiredValidator_11_4.context,
      this._PatternValidator_11_5.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_11_7 = [this._DefaultValueAccessor_11_3.context];
    this._NgModel_11_8 = new import21.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_11_6,(null as any),this._NG_VALUE_ACCESSOR_11_7);
    this._NgControl_11_9 = this._NgModel_11_8.context;
    this._NgControlStatus_11_10 = new import18.Wrapper_NgControlStatus(this._NgControl_11_9);
    this._text_12 = this.renderer.createText(this._el_9,'\n                                        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_13 = new import11.ViewContainer(13,9,this,this._anchor_13);
    this._TemplateRef_13_5 = new import15.TemplateRef_(this,13,this._anchor_13);
    this._NgIf_13_6 = new import14.Wrapper_NgIf(this._vc_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_9,'\n                                    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n                                    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                                        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'button',new import3.InlineArray4(4,'class','btn btn-warning btn-sm','type','submit'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                                            Enviar correo\n                                        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                                        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'class','btn btn-cancel btn-sm'),(null as any));
    this._RouterLinkWithHref_21_3 = new import22.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import24.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import25.LocationStrategy,this.parentView.parentIndex));
    this._text_22 = this.renderer.createText(this._el_21,'Cancelar',(null as any));
    this._text_23 = this.renderer.createText(this._el_16,'\n                                        ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._vc_24 = new import11.ViewContainer(24,16,this,this._anchor_24);
    this._TemplateRef_24_5 = new import15.TemplateRef_(this,24,this._anchor_24);
    this._NgIf_24_6 = new import14.Wrapper_NgIf(this._vc_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_16,'\n                                    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_7,'                                                                \n                                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_5,'\n                            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_5));
    this._NgForm_5_3.subscribe(this,this.eventHandler(this.handleEvent_5),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_11));
    this._NgModel_11_8.subscribe(this,this.eventHandler(this.handleEvent_11),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_21,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_21));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_3.context; }
    if (((token === import27.RequiredValidator) && (11 === requestNodeIndex))) { return this._RequiredValidator_11_4.context; }
    if (((token === import27.PatternValidator) && (11 === requestNodeIndex))) { return this._PatternValidator_11_5.context; }
    if (((token === import28.NG_VALIDATORS) && (11 === requestNodeIndex))) { return this._NG_VALIDATORS_11_6; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_7; }
    if (((token === import30.NgModel) && (11 === requestNodeIndex))) { return this._NgModel_11_8.context; }
    if (((token === import31.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_9; }
    if (((token === import32.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_10.context; }
    if (((token === import15.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import16.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import33.RouterLinkWithHref) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._RouterLinkWithHref_21_3.context; }
    if (((token === import15.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import16.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6.context; }
    if (((token === import34.NgForm) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgForm_5_3.context; }
    if (((token === import35.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ControlContainer_5_4; }
    if (((token === import32.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgControlStatusGroup_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this._DefaultValueAccessor_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = '';
    this._RequiredValidator_11_4.check_required(currVal_11_1_0,throwOnChange,false);
    this._RequiredValidator_11_4.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_2_0:any = '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$';
    this._PatternValidator_11_5.check_pattern(currVal_11_2_0,throwOnChange,false);
    this._PatternValidator_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_3_0:any = 'email';
    this._NgModel_11_8.check_name(currVal_11_3_0,throwOnChange,false);
    const currVal_11_3_1:any = this.parentView.context.userEmail;
    this._NgModel_11_8.check_model(currVal_11_3_1,throwOnChange,false);
    this._NgModel_11_8.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_10.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_13_0_0:any = (this._NgModel_11_8.context.errors && (this._NgModel_11_8.context.dirty || this._NgModel_11_8.context.touched));
    this._NgIf_13_6.check_ngIf(currVal_13_0_0,throwOnChange,false);
    this._NgIf_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    const currVal_21_0_0:any = this._arr_48('/login');
    this._RouterLinkWithHref_21_3.check_routerLink(currVal_21_0_0,throwOnChange,false);
    this._RouterLinkWithHref_21_3.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_24_0_0:any = this.parentView.context.isLoading;
    this._NgIf_24_6.check_ngIf(currVal_24_0_0,throwOnChange,false);
    this._NgIf_24_6.ngDoCheck(this,this._anchor_24,throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_24.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_5_5.checkHost(this,this,this._el_5,throwOnChange);
    this._RequiredValidator_11_4.checkHost(this,this,this._el_11,throwOnChange);
    this._PatternValidator_11_5.checkHost(this,this,this._el_11,throwOnChange);
    this._NgControlStatus_11_10.checkHost(this,this,this._el_11,throwOnChange);
    const currVal_47:any = (this.parentView.context.isLoading || this._NgForm_5_3.context.invalid);
    if (import3.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementProperty(this._el_18,'disabled',currVal_47);
      this._expr_47 = currVal_47;
    }
    this._RouterLinkWithHref_21_3.checkHost(this,this,this._el_21,throwOnChange);
  }
  destroyInternal():void {
    this._vc_13.destroyNestedViews();
    this._vc_24.destroyNestedViews();
    this._NgModel_11_8.ngOnDestroy();
    this._RouterLinkWithHref_21_3.ngOnDestroy();
    this._NgForm_5_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 13)) { return new View_ForgotPasswordComponent3(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 24)) { return new View_ForgotPasswordComponent5(this.viewUtils,this,24,this._anchor_24,this._vc_24); }
    return (null as any);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_5_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>(this._NgForm_5_3.context.form.valid && this.parentView.context.recover())) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_11_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.userEmail = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_21(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_21_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ForgotPasswordComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import22.Wrapper_RouterLinkWithHref;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_23:any;
  _arr_24:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_ForgotPasswordComponent6,renderType_ForgotPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_23 = import12.UNINITIALIZED;
    this._arr_24 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n                                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Solicitud procesada correctamente',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n                                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_2,'',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n                                Por favor comprueba el correo electrónico.\n                                ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_2,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n                            ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray2(2,'class','btn btn-warning btn-sm'),(null as any));
    this._RouterLinkWithHref_18_3 = new import22.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import24.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import25.LocationStrategy,this.parentView.parentIndex));
    this._text_19 = this.renderer.createText(this._el_18,'Regresar',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkWithHref_18_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_18_0_0:any = this._arr_24('/login');
    this._RouterLinkWithHref_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLinkWithHref_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_23:any = import3.inlineInterpolate(1,'\n                                Se envío un mensaje con instrucciones a la cuenta de correo ',this.parentView.context.userEmail,' de Resultados de Laboratorio – CediMed S.A.S.\n                                ');
    if (import3.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setText(this._text_10,currVal_23);
      this._expr_23 = currVal_23;
    }
    this._RouterLinkWithHref_18_3.checkHost(this,this,this._el_18,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_18_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_ForgotPasswordComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ForgotPasswordComponent,{});
export class View_ForgotPasswordComponent0 extends import1.AppView<import0.ForgotPasswordComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import11.ViewContainer;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import14.Wrapper_NgIf;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _vc_26:import11.ViewContainer;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import14.Wrapper_NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _vc_28:import11.ViewContainer;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import14.Wrapper_NgIf;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ForgotPasswordComponent0,renderType_ForgotPasswordComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','bgLogin'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row vertical-offset-100'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-4 col-md-offset-4'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'p',new import3.InlineArray2(2,'class','headerForm'),(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_12 = new import11.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import15.TemplateRef_(this,12,this._anchor_12);
    this._NgIf_12_6 = new import14.Wrapper_NgIf(this._vc_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'h3',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_19,'span',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'¿Olvidó su contraseña?',(null as any));
    this._text_22 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                        ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._vc_26 = new import11.ViewContainer(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import15.TemplateRef_(this,26,this._anchor_26);
    this._NgIf_26_6 = new import14.Wrapper_NgIf(this._vc_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_24,'\n                        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._vc_28 = new import11.ViewContainer(28,24,this,this._anchor_28);
    this._TemplateRef_28_5 = new import15.TemplateRef_(this,28,this._anchor_28);
    this._NgIf_28_6 = new import14.Wrapper_NgIf(this._vc_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_15,'                    \n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import16.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    if (((token === import15.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import16.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6.context; }
    if (((token === import15.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import16.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = this.context.message;
    this._NgIf_12_6.check_ngIf(currVal_12_0_0,throwOnChange,false);
    this._NgIf_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_26_0_0:boolean = !this.context.isSuccess;
    this._NgIf_26_6.check_ngIf(currVal_26_0_0,throwOnChange,false);
    this._NgIf_26_6.ngDoCheck(this,this._anchor_26,throwOnChange);
    const currVal_28_0_0:any = this.context.isSuccess;
    this._NgIf_28_6.check_ngIf(currVal_28_0_0,throwOnChange,false);
    this._NgIf_28_6.ngDoCheck(this,this._anchor_28,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_26.detectChangesInNestedViews(throwOnChange);
    this._vc_28.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
    this._vc_26.destroyNestedViews();
    this._vc_28.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_ForgotPasswordComponent1(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 26)) { return new View_ForgotPasswordComponent2(this.viewUtils,this,26,this._anchor_26,this._vc_26); }
    if ((nodeIndex == 28)) { return new View_ForgotPasswordComponent6(this.viewUtils,this,28,this._anchor_28,this._vc_28); }
    return (null as any);
  }
}