/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../angularApp/app/users/components/reset.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../angularApp/app/core/services/account.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '../../../../../angularApp/app/core/services/auth.service';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '@angular/core/src/security';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import18 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import19 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import21 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/common/src/location/location_strategy';
import * as import25 from '@angular/forms/src/directives/default_value_accessor';
import * as import26 from '@angular/forms/src/directives/validators';
import * as import27 from '@angular/forms/src/validators';
import * as import28 from '@angular/forms/src/directives/control_value_accessor';
import * as import29 from '@angular/forms/src/directives/ng_model';
import * as import30 from '@angular/forms/src/directives/ng_control';
import * as import31 from '@angular/forms/src/directives/ng_control_status';
import * as import32 from '@angular/common/src/directives/ng_if';
import * as import33 from '@angular/router/src/directives/router_link';
import * as import34 from '@angular/forms/src/directives/ng_form';
import * as import35 from '@angular/forms/src/directives/control_container';
export class Wrapper_ResetPasswordComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ResetPasswordComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.ResetPasswordComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ResetPasswordComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ResetPasswordComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ResetPasswordComponent>;
  _ResetPasswordComponent_0_3:Wrapper_ResetPasswordComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ResetPasswordComponent_Host0,renderType_ResetPasswordComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'reset-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ResetPasswordComponent0(this.viewUtils,this,0,this._el_0);
    this._ResetPasswordComponent_0_3 = new Wrapper_ResetPasswordComponent(this.injectorGet(import8.AccountService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.AuthService,this.parentIndex));
    this.compView_0.create(this._ResetPasswordComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ResetPasswordComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ResetPasswordComponent) && (0 === requestNodeIndex))) { return this._ResetPasswordComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ResetPasswordComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ResetPasswordComponentNgFactory:import7.ComponentFactory<import0.ResetPasswordComponent> = new import7.ComponentFactory<import0.ResetPasswordComponent>('reset-component',View_ResetPasswordComponent_Host0,import0.ResetPasswordComponent);
const styles_ResetPasswordComponent:any[] = ([] as any[]);
class View_ResetPasswordComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ResetPasswordComponent1,renderType_ResetPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parentView.context.message;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ResetPasswordComponent2 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ResetPasswordComponent2,renderType_ResetPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'height','24','src','/assets/spin.svg','width','24'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ResetPasswordComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ResetPasswordComponent4,renderType_ResetPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                                La contraseña es entre 4 y 20 caracteres.\n                                            ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ResetPasswordComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ResetPasswordComponent5,renderType_ResetPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','LabelError'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                                La confirmación de contraseña es incorrecta.\n                                            ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ResetPasswordComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _NgForm_5_3:import15.Wrapper_NgForm;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import16.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _DefaultValueAccessor_11_3:import17.Wrapper_DefaultValueAccessor;
  _RequiredValidator_11_4:import18.Wrapper_RequiredValidator;
  _MinLengthValidator_11_5:import18.Wrapper_MinLengthValidator;
  _MaxLengthValidator_11_6:import18.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_11_7:any[];
  _NG_VALUE_ACCESSOR_11_8:any[];
  _NgModel_11_9:import19.Wrapper_NgModel;
  _NgControl_11_10:any;
  _NgControlStatus_11_11:import16.Wrapper_NgControlStatus;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import12.ViewContainer;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import20.Wrapper_NgIf;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _DefaultValueAccessor_18_3:import17.Wrapper_DefaultValueAccessor;
  _RequiredValidator_18_4:import18.Wrapper_RequiredValidator;
  _MinLengthValidator_18_5:import18.Wrapper_MinLengthValidator;
  _MaxLengthValidator_18_6:import18.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_18_7:any[];
  _NG_VALUE_ACCESSOR_18_8:any[];
  _NgModel_18_9:import19.Wrapper_NgModel;
  _NgControl_18_10:any;
  _NgControlStatus_18_11:import16.Wrapper_NgControlStatus;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _vc_20:import12.ViewContainer;
  _TemplateRef_20_5:any;
  _NgIf_20_6:import20.Wrapper_NgIf;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _RouterLinkWithHref_28_3:import21.Wrapper_RouterLinkWithHref;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_62:any;
  _arr_63:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ResetPasswordComponent3,renderType_ResetPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_62 = import13.UNINITIALIZED;
    this._arr_63 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                Puedes crear una nueva contraseña para tener nuevamente acceso a tu cuenta.\n                            ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray4(4,'novalidate','','role','form'),(null as any));
    this._NgForm_5_3 = new import15.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_5_4 = this._NgForm_5_3.context;
    this._NgControlStatusGroup_5_5 = new import16.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n                                ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'fieldset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                                    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                                        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'input',new import3.InlineArrayDynamic(24,'autocomplete','off','autofocus','','class','form-control','id','password','maxlength','20','minlength','4','name','password','placeholder','Nueva contraseña','required','','reverse','true','type','password','validateEqual','confirmPassword'),(null as any));
    this._DefaultValueAccessor_11_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_11));
    this._RequiredValidator_11_4 = new import18.Wrapper_RequiredValidator();
    this._MinLengthValidator_11_5 = new import18.Wrapper_MinLengthValidator();
    this._MaxLengthValidator_11_6 = new import18.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_11_7 = [
      this._RequiredValidator_11_4.context,
      this._MinLengthValidator_11_5.context,
      this._MaxLengthValidator_11_6.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_11_8 = [this._DefaultValueAccessor_11_3.context];
    this._NgModel_11_9 = new import19.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_11_7,(null as any),this._NG_VALUE_ACCESSOR_11_8);
    this._NgControl_11_10 = this._NgModel_11_9.context;
    this._NgControlStatus_11_11 = new import16.Wrapper_NgControlStatus(this._NgControl_11_10);
    this._text_12 = this.renderer.createText(this._el_9,'\n                                        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_13 = new import12.ViewContainer(13,9,this,this._anchor_13);
    this._TemplateRef_13_5 = new import23.TemplateRef_(this,13,this._anchor_13);
    this._NgIf_13_6 = new import20.Wrapper_NgIf(this._vc_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_9,'\n                                    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n                                    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                                        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'input',new import3.InlineArrayDynamic(20,'autocomplete','off','class','form-control','id','confirmPassword','maxlength','20','minlength','4','name','confirmPassword','placeholder','Confirmar contraseña','required','','type','password','validateEqual','password'),(null as any));
    this._DefaultValueAccessor_18_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_18));
    this._RequiredValidator_18_4 = new import18.Wrapper_RequiredValidator();
    this._MinLengthValidator_18_5 = new import18.Wrapper_MinLengthValidator();
    this._MaxLengthValidator_18_6 = new import18.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_18_7 = [
      this._RequiredValidator_18_4.context,
      this._MinLengthValidator_18_5.context,
      this._MaxLengthValidator_18_6.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_18_8 = [this._DefaultValueAccessor_18_3.context];
    this._NgModel_18_9 = new import19.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_18_7,(null as any),this._NG_VALUE_ACCESSOR_18_8);
    this._NgControl_18_10 = this._NgModel_18_9.context;
    this._NgControlStatus_18_11 = new import16.Wrapper_NgControlStatus(this._NgControl_18_10);
    this._text_19 = this.renderer.createText(this._el_16,'\n                                        ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._vc_20 = new import12.ViewContainer(20,16,this,this._anchor_20);
    this._TemplateRef_20_5 = new import23.TemplateRef_(this,20,this._anchor_20);
    this._NgIf_20_6 = new import20.Wrapper_NgIf(this._vc_20.vcRef,this._TemplateRef_20_5);
    this._text_21 = this.renderer.createText(this._el_16,'\n                                    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_7,' \n                                    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n                                        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'button',new import3.InlineArray4(4,'class','btn btn-warning btn-sm','type','button'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                                            Cambiar contraseña\n                                        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n                                        ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_23,'a',new import3.InlineArray2(2,'class','btn btn-cancel btn-sm'),(null as any));
    this._RouterLinkWithHref_28_3 = new import21.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import10.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import24.LocationStrategy,this.parentView.parentIndex));
    this._text_29 = this.renderer.createText(this._el_28,'Cancelar',(null as any));
    this._text_30 = this.renderer.createText(this._el_23,'                                    \n                                    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_7,'                             \n                                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_5,'\n                            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_5));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_11));
    this._NgModel_11_9.subscribe(this,this.eventHandler(this.handleEvent_11),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_18));
    this._NgModel_18_9.subscribe(this,this.eventHandler(this.handleEvent_18),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_25));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_3.context; }
    if (((token === import26.RequiredValidator) && (11 === requestNodeIndex))) { return this._RequiredValidator_11_4.context; }
    if (((token === import26.MinLengthValidator) && (11 === requestNodeIndex))) { return this._MinLengthValidator_11_5.context; }
    if (((token === import26.MaxLengthValidator) && (11 === requestNodeIndex))) { return this._MaxLengthValidator_11_6.context; }
    if (((token === import27.NG_VALIDATORS) && (11 === requestNodeIndex))) { return this._NG_VALIDATORS_11_7; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_8; }
    if (((token === import29.NgModel) && (11 === requestNodeIndex))) { return this._NgModel_11_9.context; }
    if (((token === import30.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_10; }
    if (((token === import31.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_11.context; }
    if (((token === import23.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import32.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import25.DefaultValueAccessor) && (18 === requestNodeIndex))) { return this._DefaultValueAccessor_18_3.context; }
    if (((token === import26.RequiredValidator) && (18 === requestNodeIndex))) { return this._RequiredValidator_18_4.context; }
    if (((token === import26.MinLengthValidator) && (18 === requestNodeIndex))) { return this._MinLengthValidator_18_5.context; }
    if (((token === import26.MaxLengthValidator) && (18 === requestNodeIndex))) { return this._MaxLengthValidator_18_6.context; }
    if (((token === import27.NG_VALIDATORS) && (18 === requestNodeIndex))) { return this._NG_VALIDATORS_18_7; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (18 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_18_8; }
    if (((token === import29.NgModel) && (18 === requestNodeIndex))) { return this._NgModel_18_9.context; }
    if (((token === import30.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_10; }
    if (((token === import31.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_11.context; }
    if (((token === import23.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import32.NgIf) && (20 === requestNodeIndex))) { return this._NgIf_20_6.context; }
    if (((token === import33.RouterLinkWithHref) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkWithHref_28_3.context; }
    if (((token === import34.NgForm) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgForm_5_3.context; }
    if (((token === import35.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ControlContainer_5_4; }
    if (((token === import31.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControlStatusGroup_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this._DefaultValueAccessor_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = '';
    this._RequiredValidator_11_4.check_required(currVal_11_1_0,throwOnChange,false);
    this._RequiredValidator_11_4.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_2_0:any = '4';
    this._MinLengthValidator_11_5.check_minlength(currVal_11_2_0,throwOnChange,false);
    this._MinLengthValidator_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_3_0:any = '20';
    this._MaxLengthValidator_11_6.check_maxlength(currVal_11_3_0,throwOnChange,false);
    this._MaxLengthValidator_11_6.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_4_0:any = 'password';
    this._NgModel_11_9.check_name(currVal_11_4_0,throwOnChange,false);
    const currVal_11_4_1:any = this.parentView.context.user.password;
    this._NgModel_11_9.check_model(currVal_11_4_1,throwOnChange,false);
    this._NgModel_11_9.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_11.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_13_0_0:any = (this._NgModel_11_9.context.errors && (this._NgModel_11_9.context.dirty || this._NgModel_11_9.context.touched));
    this._NgIf_13_6.check_ngIf(currVal_13_0_0,throwOnChange,false);
    this._NgIf_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    this._DefaultValueAccessor_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_1_0:any = '';
    this._RequiredValidator_18_4.check_required(currVal_18_1_0,throwOnChange,false);
    this._RequiredValidator_18_4.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_2_0:any = '4';
    this._MinLengthValidator_18_5.check_minlength(currVal_18_2_0,throwOnChange,false);
    this._MinLengthValidator_18_5.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_3_0:any = '20';
    this._MaxLengthValidator_18_6.check_maxlength(currVal_18_3_0,throwOnChange,false);
    this._MaxLengthValidator_18_6.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_4_0:any = 'confirmPassword';
    this._NgModel_18_9.check_name(currVal_18_4_0,throwOnChange,false);
    const currVal_18_4_1:any = this.parentView.context.user.confirmPassword;
    this._NgModel_18_9.check_model(currVal_18_4_1,throwOnChange,false);
    this._NgModel_18_9.ngDoCheck(this,this._el_18,throwOnChange);
    this._NgControlStatus_18_11.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_20_0_0:any = (this._NgModel_18_9.context.errors && (this._NgModel_18_9.context.dirty || this._NgModel_18_9.context.touched));
    this._NgIf_20_6.check_ngIf(currVal_20_0_0,throwOnChange,false);
    this._NgIf_20_6.ngDoCheck(this,this._anchor_20,throwOnChange);
    const currVal_28_0_0:any = this._arr_63('/login');
    this._RouterLinkWithHref_28_3.check_routerLink(currVal_28_0_0,throwOnChange,false);
    this._RouterLinkWithHref_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_5_5.checkHost(this,this,this._el_5,throwOnChange);
    this._RequiredValidator_11_4.checkHost(this,this,this._el_11,throwOnChange);
    this._MinLengthValidator_11_5.checkHost(this,this,this._el_11,throwOnChange);
    this._MaxLengthValidator_11_6.checkHost(this,this,this._el_11,throwOnChange);
    this._NgControlStatus_11_11.checkHost(this,this,this._el_11,throwOnChange);
    this._RequiredValidator_18_4.checkHost(this,this,this._el_18,throwOnChange);
    this._MinLengthValidator_18_5.checkHost(this,this,this._el_18,throwOnChange);
    this._MaxLengthValidator_18_6.checkHost(this,this,this._el_18,throwOnChange);
    this._NgControlStatus_18_11.checkHost(this,this,this._el_18,throwOnChange);
    const currVal_62:any = (this.parentView.context.isLoading || this._NgForm_5_3.context.invalid);
    if (import3.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementProperty(this._el_25,'disabled',currVal_62);
      this._expr_62 = currVal_62;
    }
    this._RouterLinkWithHref_28_3.checkHost(this,this,this._el_28,throwOnChange);
  }
  destroyInternal():void {
    this._vc_13.destroyNestedViews();
    this._vc_20.destroyNestedViews();
    this._NgModel_11_9.ngOnDestroy();
    this._NgModel_18_9.ngOnDestroy();
    this._RouterLinkWithHref_28_3.ngOnDestroy();
    this._NgForm_5_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 13)) { return new View_ResetPasswordComponent4(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 20)) { return new View_ResetPasswordComponent5(this.viewUtils,this,20,this._anchor_20,this._vc_20); }
    return (null as any);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_5_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_11_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.user.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_18_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.user.confirmPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.changePassword()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_28_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ResetPasswordComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import21.Wrapper_RouterLinkWithHref;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _arr_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_ResetPasswordComponent6,renderType_ResetPasswordComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._arr_12 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                    La contraseña ha sido cambiada exitosamente.\n                                ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'a',new import3.InlineArray2(2,'class','btn btn-warning'),(null as any));
    this._RouterLinkWithHref_7_3 = new import21.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import9.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import10.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import24.LocationStrategy,this.parentView.parentIndex));
    this._text_8 = this.renderer.createText(this._el_7,'Regresar',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n                                ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7_0_0:any = this._arr_12('/login');
    this._RouterLinkWithHref_7_3.check_routerLink(currVal_7_0_0,throwOnChange,false);
    this._RouterLinkWithHref_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._RouterLinkWithHref_7_3.checkHost(this,this,this._el_7,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_7_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_ResetPasswordComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ResetPasswordComponent,{});
export class View_ResetPasswordComponent0 extends import1.AppView<import0.ResetPasswordComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import12.ViewContainer;
  _TemplateRef_12_5:any;
  _NgIf_12_6:import20.Wrapper_NgIf;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import12.ViewContainer;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import20.Wrapper_NgIf;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _vc_28:import12.ViewContainer;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import20.Wrapper_NgIf;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _vc_30:import12.ViewContainer;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import20.Wrapper_NgIf;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ResetPasswordComponent0,renderType_ResetPasswordComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','bgLogin'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row vertical-offset-100'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-4 col-md-offset-4'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'p',new import3.InlineArray2(2,'class','headerForm'),(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_6,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_12 = new import12.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import23.TemplateRef_(this,12,this._anchor_12);
    this._NgIf_12_6 = new import20.Wrapper_NgIf(this._vc_12.vcRef,this._TemplateRef_12_5);
    this._text_13 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'h3',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_19,'span',new import3.InlineArray2(2,'class','title'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Restablecer contraseña',(null as any));
    this._text_22 = this.renderer.createText(this._el_17,'\n                        ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_17,(null as any));
    this._vc_23 = new import12.ViewContainer(23,17,this,this._anchor_23);
    this._TemplateRef_23_5 = new import23.TemplateRef_(this,23,this._anchor_23);
    this._NgIf_23_6 = new import20.Wrapper_NgIf(this._vc_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._text_25 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._vc_28 = new import12.ViewContainer(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import23.TemplateRef_(this,28,this._anchor_28);
    this._NgIf_28_6 = new import20.Wrapper_NgIf(this._vc_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_26,'\n                        ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._vc_30 = new import12.ViewContainer(30,26,this,this._anchor_30);
    this._TemplateRef_30_5 = new import23.TemplateRef_(this,30,this._anchor_30);
    this._NgIf_30_6 = new import20.Wrapper_NgIf(this._vc_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_15,'                    \n                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_34 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import32.NgIf) && (12 === requestNodeIndex))) { return this._NgIf_12_6.context; }
    if (((token === import23.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import32.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import23.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import32.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    if (((token === import23.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import32.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = this.context.message;
    this._NgIf_12_6.check_ngIf(currVal_12_0_0,throwOnChange,false);
    this._NgIf_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_23_0_0:any = this.context.isLoading;
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    const currVal_28_0_0:any = (this.context.isConfirmed && !this.context.isPasswordChanged);
    this._NgIf_28_6.check_ngIf(currVal_28_0_0,throwOnChange,false);
    this._NgIf_28_6.ngDoCheck(this,this._anchor_28,throwOnChange);
    const currVal_30_0_0:any = this.context.isPasswordChanged;
    this._NgIf_30_6.check_ngIf(currVal_30_0_0,throwOnChange,false);
    this._NgIf_30_6.ngDoCheck(this,this._anchor_30,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    this._vc_28.detectChangesInNestedViews(throwOnChange);
    this._vc_30.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
    this._vc_23.destroyNestedViews();
    this._vc_28.destroyNestedViews();
    this._vc_30.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_ResetPasswordComponent1(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 23)) { return new View_ResetPasswordComponent2(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    if ((nodeIndex == 28)) { return new View_ResetPasswordComponent3(this.viewUtils,this,28,this._anchor_28,this._vc_28); }
    if ((nodeIndex == 30)) { return new View_ResetPasswordComponent6(this.viewUtils,this,30,this._anchor_30,this._vc_30); }
    return (null as any);
  }
}